CREATE table countries (countryname varchar(40) primary key, currency varchar(25), isd integer);
INSERT INTO countries values ('Afghanistan','Afghani',1);
INSERT INTO countries values ('Albania','Lek',2);
INSERT INTO countries values ('Algeria','Dinar',3);
INSERT INTO countries values ('Andorra','Euro',4);
INSERT INTO countries values ('Angola','New Kwanza',5);
INSERT INTO countries values ('Antigua and Barbuda','East Caribbean dollar',6);
INSERT INTO countries values ('Argentina','Peso',7);
INSERT INTO countries values ('Armenia','Dram',8);
INSERT INTO countries values ('Australia','Australian dollar',9);
INSERT INTO countries values ('Austria','Euro',10);
INSERT INTO countries values ('Azerbaijan','Manat',11);
INSERT INTO countries values ('Bahamas','Bahamian dollar',12);
INSERT INTO countries values ('Bahrain','Bahrain dinar',13);
INSERT INTO countries values ('Bangladesh','Taka',14);
INSERT INTO countries values ('Barbados','Barbados dollar',15);
INSERT INTO countries values ('Belarus','Belorussian ruble',16);
INSERT INTO countries values ('Belgium','Euro',17);
INSERT INTO countries values ('Belize','Belize dollar',18);
INSERT INTO countries values ('Benin','CFA Franc',19);
INSERT INTO countries values ('Bhutan','Ngultrum',20);
INSERT INTO countries values ('Bolivia','Boliviano',21);
INSERT INTO countries values ('Bosnia and Herzegovina','Marka',22);
INSERT INTO countries values ('Botswana','Pula',23);
INSERT INTO countries values ('Brazil','Real',24);
INSERT INTO countries values ('Brunei','Brunei dollar',25);
INSERT INTO countries values ('Bulgaria','Lev',26);
INSERT INTO countries values ('Burkina Faso','CFA Franc',27);
INSERT INTO countries values ('Burundi','Burundi franc',28);
INSERT INTO countries values ('Cambodia','Riel',29);
INSERT INTO countries values ('Cameroon','CFA Franc',30);
INSERT INTO countries values ('Canada','Canadian dollar',31);
INSERT INTO countries values ('Cape Verde','Cape Verdean escudo',32);
INSERT INTO countries values ('Central African Republic','CFA Franc',33);
INSERT INTO countries values ('Chad','CFA Franc',34);
INSERT INTO countries values ('Chile','Chilean Peso',35);
INSERT INTO countries values ('China','Yuan/Renminbi',36);
INSERT INTO countries values ('Colombia','Colombian Peso',37);
INSERT INTO countries values ('Comoros','Franc',38);
INSERT INTO countries values ('Congo','Congolese franc',39);
INSERT INTO countries values ('Republic of Congo','CFA Franc',40);
INSERT INTO countries values ('Costa Rica','Colón',41);
INSERT INTO countries values ('Côte dIvoire','CFA Franc',42);
INSERT INTO countries values ('Croatia','Kuna',43);
INSERT INTO countries values ('Cuba','Cuban Peso',44);
INSERT INTO countries values ('Cyprus','Cyprus pound',45);
INSERT INTO countries values ('Czech Republic','Koruna',46);
INSERT INTO countries values ('Denmark','Krone',47);
INSERT INTO countries values ('Djibouti','Djibouti franc',48);
INSERT INTO countries values ('Dominica','East Caribbean dollar',49);
INSERT INTO countries values ('Dominican Republic','Dominican Peso',50);
INSERT INTO countries values ('East Timor','U.S. dollar',51);
INSERT INTO countries values ('Ecuador','US dollar',52);
INSERT INTO countries values ('Egypt','Egyptian pound',53);
INSERT INTO countries values ('El Salvador','U.S. dollar',54);
INSERT INTO countries values ('Equatorial Guinea','CFA Franc',55);
INSERT INTO countries values ('Eritrea','Nakfa',56);
INSERT INTO countries values ('Estonia','Kroon',57);
INSERT INTO countries values ('Ethiopia','Birr',58);
INSERT INTO countries values ('Fiji','Fiji dollar',59);
INSERT INTO countries values ('Finland','Euro',60);
INSERT INTO countries values ('France','Euro',61);
INSERT INTO countries values ('Gabon','CFA Franc',62);
INSERT INTO countries values ('Gambia','Dalasi',63);
INSERT INTO countries values ('Georgia','Lari',64);
INSERT INTO countries values ('Germany','Euro',65);
INSERT INTO countries values ('Ghana','Cedi',66);
INSERT INTO countries values ('Greece','Euro',67);
INSERT INTO countries values ('Grenada','East Caribbean dollar',68);
INSERT INTO countries values ('Guatemala','Quetzal',69);
INSERT INTO countries values ('Guinea','Guinean franc',70);
INSERT INTO countries values ('Guinea-Bissau','CFA Franc',71);
INSERT INTO countries values ('Guyana','Guyanese dollar',72);
INSERT INTO countries values ('Haiti','Gourde',73);
INSERT INTO countries values ('Honduras','Lempira',74);
INSERT INTO countries values ('Hungary','Forint',75);
INSERT INTO countries values ('Iceland','Icelandic króna',76);
INSERT INTO countries values ('India','Rupee',91);
INSERT INTO countries values ('Indonesia','Rupiah',77);
INSERT INTO countries values ('Iran','Rial',78);
INSERT INTO countries values ('Iraq','US dollar',79);
INSERT INTO countries values ('Ireland','Euro',80);
INSERT INTO countries values ('Israel','Shekel',81);
INSERT INTO countries values ('Italy','Euro',82);
INSERT INTO countries values ('Jamaica','Jamaican dollar',83);
INSERT INTO countries values ('Japan','Yen',84);
INSERT INTO countries values ('Jordan','Jordanian dinar',85);
INSERT INTO countries values ('Kazakhstan','Tenge',86);
INSERT INTO countries values ('Kenya','Kenya shilling',87);
INSERT INTO countries values ('Kiribati','Australian dollar',88);
INSERT INTO countries values ('North Korea','Won',89);
INSERT INTO countries values ('South Korea','Won',90);
INSERT INTO countries values ('Kuwait','Kuwaiti dinar',92);
INSERT INTO countries values ('Kyrgyzstan','Som',93);
INSERT INTO countries values ('Laos','New Kip',94);
INSERT INTO countries values ('Latvia','Lats',95);
INSERT INTO countries values ('Lebanon','Lebanese pound',96);
INSERT INTO countries values ('Lesotho','Maluti',97);
INSERT INTO countries values ('Liberia','Liberian dollar',98);
INSERT INTO countries values ('Libya','Libyan dinar',99);
INSERT INTO countries values ('Liechtenstein','Swiss franc',100);
INSERT INTO countries values ('Lithuania','Litas',101);
INSERT INTO countries values ('Luxembourg','Euro',102);
INSERT INTO countries values ('Macedonia','Denar',103);
INSERT INTO countries values ('Madagascar','Malagasy franc',104);
INSERT INTO countries values ('Malawi','Kwacha',105);
INSERT INTO countries values ('Malaysia','Ringgit',106);
INSERT INTO countries values ('Maldives','Rufiya',107);
INSERT INTO countries values ('Mali','CFA Franc',108);
INSERT INTO countries values ('Malta','Euro',109);
INSERT INTO countries values ('Mauritania','Ouguiya',110);
INSERT INTO countries values ('Mauritius','Mauritian rupee',111);
INSERT INTO countries values ('Mexico','Mexican peso',112);
INSERT INTO countries values ('Moldova','Leu',113);
INSERT INTO countries values ('Monaco','Euro',114);
INSERT INTO countries values ('Mongolia','Tugrik',115);
INSERT INTO countries values ('Montenegro','Euro',116);
INSERT INTO countries values ('Morocco','Dirham',117);
INSERT INTO countries values ('Mozambique','Metical',118);
INSERT INTO countries values ('Myanmar','Kyat',119);
INSERT INTO countries values ('Namibia','Namibian dollar',120);
INSERT INTO countries values ('Nauru','Australian dollar',121);
INSERT INTO countries values ('Nepal','Nepalese rupee',122);
INSERT INTO countries values ('Netherlands','Euro',123);
INSERT INTO countries values ('New Zealand','New Zealand dollar',124);
INSERT INTO countries values ('Nicaragua','Gold cordoba',125);
INSERT INTO countries values ('Niger','CFA Franc',126);
INSERT INTO countries values ('Nigeria','Naira',127);
INSERT INTO countries values ('Norway','Norwegian krone',128);
INSERT INTO countries values ('Oman','Omani rial',129);
INSERT INTO countries values ('Pakistan','Pakistan rupee',130);
INSERT INTO countries values ('Palau','US dollar',131);
INSERT INTO countries values ('Palestinian State','Jordanian dinars',132);
INSERT INTO countries values ('Panama balboa',' US dollar',133);
INSERT INTO countries values ('Papua New Guinea','Kina',134);
INSERT INTO countries values ('Paraguay','Guaraní',135);
INSERT INTO countries values ('Peru','Nuevo sol',136);
INSERT INTO countries values ('Philippines','Peso',137);
INSERT INTO countries values ('Poland','Zloty',138);
INSERT INTO countries values ('Portugal','Euro',139);
INSERT INTO countries values ('Qatar','Qatari riyal',140);
INSERT INTO countries values ('Romania','Leu',141);
INSERT INTO countries values ('Russia','Ruble',142);
INSERT INTO countries values ('Rwanda','Rwanda franc',143);
INSERT INTO countries values ('St. Kitts and Nevis','East Caribbean dollar',144);
INSERT INTO countries values ('St. Lucia','East Caribbean dollar',145);
INSERT INTO countries values ('St. Vincent and the Grenadines','East Caribbean dollar',146);
INSERT INTO countries values ('Samoa','Tala',147);
INSERT INTO countries values ('San Marino','Euro',148);
INSERT INTO countries values ('São Tomé and Príncipe','Dobra',149);
INSERT INTO countries values ('Saudi Arabia','Riyal',150);
INSERT INTO countries values ('Senegal','CFA Franc',151);
INSERT INTO countries values ('Serbia Yugoslav',' new dinar',152);
INSERT INTO countries values ('Seychelles','Seychelles rupee',153);
INSERT INTO countries values ('Sierra Leone','Leone',154);
INSERT INTO countries values ('Singapore','Singapore dollar',155);
INSERT INTO countries values ('Slovakia','Koruna',156);
INSERT INTO countries values ('Slovenia','Slovenian tolar',157);
INSERT INTO countries values ('Solomon Islands','Solomon Islands dollar',158);
INSERT INTO countries values ('Somalia','Somali shilling',159);
INSERT INTO countries values ('South Africa','Rand',160);
INSERT INTO countries values ('Spain','Euro',161);
INSERT INTO countries values ('Sri Lanka','Sri Lanka rupee',162);
INSERT INTO countries values ('Sudan','Dinar',163);
INSERT INTO countries values ('Suriname','Surinamese dollar',164);
INSERT INTO countries values ('Swaziland','Lilangeni',165);
INSERT INTO countries values ('Sweden','Krona',166);
INSERT INTO countries values ('Switzerland','Swiss franc',167);
INSERT INTO countries values ('Syria','Syrian pound',168);
INSERT INTO countries values ('Taiwan','Taiwan dollar',169);
INSERT INTO countries values ('Tajikistan','somoni',170);
INSERT INTO countries values ('Tanzania','Tanzanian shilling',171);
INSERT INTO countries values ('Thailand','baht',172);
INSERT INTO countries values ('Togo','CFA Franc',173);
INSERT INTO countries values ('Tonga','Paanga',174);
INSERT INTO countries values ('TrinidadTobago','TrinidadTobagodollar',175);
INSERT INTO countries values ('Tunisia','Tunisian dinar',176);
INSERT INTO countries values ('Turkey','Turkish lira',177);
INSERT INTO countries values ('Turkmenistan','Manat',178);
INSERT INTO countries values ('Tuvalu','Australian dollar',179);
INSERT INTO countries values ('Uganda','Ugandan new shilling',180);
INSERT INTO countries values ('Ukraine','Hryvna',181);
INSERT INTO countries values ('United Arab Emirates','U.A.E. dirham',182);
INSERT INTO countries values ('United Kingdom','Pound sterling',183);
INSERT INTO countries values ('United States','dollar',184);
INSERT INTO countries values ('Uruguay','Uruguay peso',185);
INSERT INTO countries values ('Uzbekistan','Uzbekistani sum',186);
INSERT INTO countries values ('Vanuatu','Vatu',187);
INSERT INTO countries values ('Vatican City','Euro',188);
INSERT INTO countries values ('Venezuela','Bolivar',189);
INSERT INTO countries values ('Vietnam','Dong',190);
INSERT INTO countries values ('Sahara','Tala',191);
INSERT INTO countries values ('Yemen','Rial',192);
INSERT INTO countries values ('Zambia','Kwacha',193);
INSERT INTO countries values ('Zimbabwe','Zimbabwean dollar',194);
