'Afghanistan','s1'
'Afghanistan','s2'
'Afghanistan','s3'
'Afghanistan','s4'
'Afghanistan','s5'
'Afghanistan','s6'
'Afghanistan','s7'
'Afghanistan','s8'
'Afghanistan','s9'
'Afghanistan','s10'
'Afghanistan','s11'
'Afghanistan','s12'
'Afghanistan','s13'
'Afghanistan','s14'
'Afghanistan','s15'
'Afghanistan','s16'
'Afghanistan','s17'
'Afghanistan','s18'
'Afghanistan','s19'
'Afghanistan','s20'
'Afghanistan','s21'
'Afghanistan','s22'
'Afghanistan','s23'
'Albania','s1'
'Albania','s2'
'Albania','s3'
'Albania','s4'
'Albania','s5'
'Albania','s6'
'Albania','s7'
'Albania','s8'
'Albania','s9'
'Albania','s10'
'Albania','s11'
'Albania','s12'
'Albania','s13'
'Albania','s14'
'Albania','s15'
'Albania','s16'
'Albania','s17'
'Albania','s18'
'Albania','s19'
'Albania','s20'
'Albania','s21'
'Albania','s22'
'Albania','s23'
'Albania','s24'
'Albania','s25'
'Albania','s26'
'Algeria','s1'
'Algeria','s2'
'Algeria','s3'
'Algeria','s4'
'Algeria','s5'
'Algeria','s6'
'Algeria','s7'
'Algeria','s8'
'Algeria','s9'
'Algeria','s10'
'Algeria','s11'
'Algeria','s12'
'Algeria','s13'
'Algeria','s14'
'Algeria','s15'
'Algeria','s16'
'Algeria','s17'
'Algeria','s18'
'Algeria','s19'
'Algeria','s20'
'Algeria','s21'
'Algeria','s22'
'Algeria','s23'
'Algeria','s24'
'Algeria','s25'
'Algeria','s26'
'Algeria','s27'
'Andorra','s1'
'Andorra','s2'
'Andorra','s3'
'Andorra','s4'
'Andorra','s5'
'Andorra','s6'
'Andorra','s7'
'Andorra','s8'
'Andorra','s9'
'Andorra','s10'
'Andorra','s11'
'Andorra','s12'
'Andorra','s13'
'Andorra','s14'
'Andorra','s15'
'Andorra','s16'
'Andorra','s17'
'Andorra','s18'
'Andorra','s19'
'Andorra','s20'
'Andorra','s21'
'Andorra','s22'
'Andorra','s23'
'Andorra','s24'
'Andorra','s25'
'Angola','s1'
'Angola','s2'
'Angola','s3'
'Angola','s4'
'Angola','s5'
'Angola','s6'
'Angola','s7'
'Angola','s8'
'Angola','s9'
'Angola','s10'
'Angola','s11'
'Angola','s12'
'Angola','s13'
'Angola','s14'
'Angola','s15'
'Angola','s16'
'Angola','s17'
'Angola','s18'
'Angola','s19'
'Angola','s20'
'Angola','s21'
'Angola','s22'
'Angola','s23'
'Antigua and Barbuda','s1'
'Antigua and Barbuda','s2'
'Antigua and Barbuda','s3'
'Antigua and Barbuda','s4'
'Antigua and Barbuda','s5'
'Antigua and Barbuda','s6'
'Antigua and Barbuda','s7'
'Antigua and Barbuda','s8'
'Antigua and Barbuda','s9'
'Antigua and Barbuda','s10'
'Antigua and Barbuda','s11'
'Antigua and Barbuda','s12'
'Antigua and Barbuda','s13'
'Antigua and Barbuda','s14'
'Antigua and Barbuda','s15'
'Antigua and Barbuda','s16'
'Antigua and Barbuda','s17'
'Antigua and Barbuda','s18'
'Antigua and Barbuda','s19'
'Antigua and Barbuda','s20'
'Antigua and Barbuda','s21'
'Antigua and Barbuda','s22'
'Antigua and Barbuda','s23'
'Antigua and Barbuda','s24'
'Antigua and Barbuda','s25'
'Argentina','s1'
'Argentina','s2'
'Argentina','s3'
'Argentina','s4'
'Argentina','s5'
'Argentina','s6'
'Argentina','s7'
'Argentina','s8'
'Argentina','s9'
'Argentina','s10'
'Argentina','s11'
'Argentina','s12'
'Argentina','s13'
'Argentina','s14'
'Argentina','s15'
'Argentina','s16'
'Argentina','s17'
'Argentina','s18'
'Argentina','s19'
'Argentina','s20'
'Argentina','s21'
'Argentina','s22'
'Argentina','s23'
'Argentina','s24'
'Argentina','s25'
'Argentina','s26'
'Armenia','s1'
'Armenia','s2'
'Armenia','s3'
'Armenia','s4'
'Armenia','s5'
'Armenia','s6'
'Armenia','s7'
'Armenia','s8'
'Armenia','s9'
'Armenia','s10'
'Armenia','s11'
'Armenia','s12'
'Armenia','s13'
'Armenia','s14'
'Armenia','s15'
'Armenia','s16'
'Armenia','s17'
'Armenia','s18'
'Armenia','s19'
'Armenia','s20'
'Armenia','s21'
'Armenia','s22'
'Australia','s1'
'Australia','s2'
'Australia','s3'
'Australia','s4'
'Australia','s5'
'Australia','s6'
'Australia','s7'
'Australia','s8'
'Australia','s9'
'Australia','s10'
'Australia','s11'
'Australia','s12'
'Australia','s13'
'Australia','s14'
'Australia','s15'
'Australia','s16'
'Australia','s17'
'Australia','s18'
'Australia','s19'
'Australia','s20'
'Australia','s21'
'Australia','s22'
'Australia','s23'
'Australia','s24'
'Australia','s25'
'Australia','s26'
'Australia','s27'
'Australia','s28'
'Australia','s29'
'Austria','s1'
'Austria','s2'
'Austria','s3'
'Austria','s4'
'Austria','s5'
'Austria','s6'
'Austria','s7'
'Austria','s8'
'Austria','s9'
'Austria','s10'
'Austria','s11'
'Austria','s12'
'Austria','s13'
'Austria','s14'
'Austria','s15'
'Austria','s16'
'Austria','s17'
'Austria','s18'
'Austria','s19'
'Austria','s20'
'Austria','s21'
'Azerbaijan','s1'
'Azerbaijan','s2'
'Azerbaijan','s3'
'Azerbaijan','s4'
'Azerbaijan','s5'
'Azerbaijan','s6'
'Azerbaijan','s7'
'Azerbaijan','s8'
'Azerbaijan','s9'
'Azerbaijan','s10'
'Azerbaijan','s11'
'Azerbaijan','s12'
'Azerbaijan','s13'
'Azerbaijan','s14'
'Azerbaijan','s15'
'Azerbaijan','s16'
'Azerbaijan','s17'
'Azerbaijan','s18'
'Azerbaijan','s19'
'Azerbaijan','s20'
'Azerbaijan','s21'
'Azerbaijan','s22'
'Bahamas','s1'
'Bahamas','s2'
'Bahamas','s3'
'Bahamas','s4'
'Bahamas','s5'
'Bahamas','s6'
'Bahamas','s7'
'Bahamas','s8'
'Bahamas','s9'
'Bahamas','s10'
'Bahamas','s11'
'Bahamas','s12'
'Bahamas','s13'
'Bahamas','s14'
'Bahamas','s15'
'Bahamas','s16'
'Bahamas','s17'
'Bahamas','s18'
'Bahamas','s19'
'Bahamas','s20'
'Bahamas','s21'
'Bahamas','s22'
'Bahamas','s23'
'Bahamas','s24'
'Bahamas','s25'
'Bahamas','s26'
'Bahamas','s27'
'Bahrain','s1'
'Bahrain','s2'
'Bahrain','s3'
'Bahrain','s4'
'Bahrain','s5'
'Bahrain','s6'
'Bahrain','s7'
'Bahrain','s8'
'Bahrain','s9'
'Bahrain','s10'
'Bahrain','s11'
'Bahrain','s12'
'Bahrain','s13'
'Bahrain','s14'
'Bahrain','s15'
'Bahrain','s16'
'Bahrain','s17'
'Bahrain','s18'
'Bahrain','s19'
'Bahrain','s20'
'Bangladesh','s1'
'Bangladesh','s2'
'Bangladesh','s3'
'Bangladesh','s4'
'Bangladesh','s5'
'Bangladesh','s6'
'Bangladesh','s7'
'Bangladesh','s8'
'Bangladesh','s9'
'Bangladesh','s10'
'Bangladesh','s11'
'Bangladesh','s12'
'Bangladesh','s13'
'Bangladesh','s14'
'Bangladesh','s15'
'Bangladesh','s16'
'Bangladesh','s17'
'Bangladesh','s18'
'Bangladesh','s19'
'Bangladesh','s20'
'Bangladesh','s21'
'Bangladesh','s22'
'Bangladesh','s23'
'Bangladesh','s24'
'Bangladesh','s25'
'Bangladesh','s26'
'Bangladesh','s27'
'Bangladesh','s28'
'Bangladesh','s29'
'Barbados','s1'
'Barbados','s2'
'Barbados','s3'
'Barbados','s4'
'Barbados','s5'
'Barbados','s6'
'Barbados','s7'
'Barbados','s8'
'Barbados','s9'
'Barbados','s10'
'Barbados','s11'
'Barbados','s12'
'Barbados','s13'
'Barbados','s14'
'Barbados','s15'
'Barbados','s16'
'Barbados','s17'
'Barbados','s18'
'Barbados','s19'
'Barbados','s20'
'Barbados','s21'
'Barbados','s22'
'Barbados','s23'
'Belarus','s1'
'Belarus','s2'
'Belarus','s3'
'Belarus','s4'
'Belarus','s5'
'Belarus','s6'
'Belarus','s7'
'Belarus','s8'
'Belarus','s9'
'Belarus','s10'
'Belarus','s11'
'Belarus','s12'
'Belarus','s13'
'Belarus','s14'
'Belarus','s15'
'Belarus','s16'
'Belarus','s17'
'Belarus','s18'
'Belarus','s19'
'Belarus','s20'
'Belarus','s21'
'Belarus','s22'
'Belarus','s23'
'Belarus','s24'
'Belarus','s25'
'Belarus','s26'
'Belgium','s1'
'Belgium','s2'
'Belgium','s3'
'Belgium','s4'
'Belgium','s5'
'Belgium','s6'
'Belgium','s7'
'Belgium','s8'
'Belgium','s9'
'Belgium','s10'
'Belgium','s11'
'Belgium','s12'
'Belgium','s13'
'Belgium','s14'
'Belgium','s15'
'Belgium','s16'
'Belgium','s17'
'Belgium','s18'
'Belgium','s19'
'Belgium','s20'
'Belize','s1'
'Belize','s2'
'Belize','s3'
'Belize','s4'
'Belize','s5'
'Belize','s6'
'Belize','s7'
'Belize','s8'
'Belize','s9'
'Belize','s10'
'Belize','s11'
'Belize','s12'
'Belize','s13'
'Belize','s14'
'Belize','s15'
'Belize','s16'
'Belize','s17'
'Belize','s18'
'Belize','s19'
'Belize','s20'
'Belize','s21'
'Belize','s22'
'Belize','s23'
'Belize','s24'
'Belize','s25'
'Belize','s26'
'Benin','s1'
'Benin','s2'
'Benin','s3'
'Benin','s4'
'Benin','s5'
'Benin','s6'
'Benin','s7'
'Benin','s8'
'Benin','s9'
'Benin','s10'
'Benin','s11'
'Benin','s12'
'Benin','s13'
'Benin','s14'
'Benin','s15'
'Benin','s16'
'Benin','s17'
'Benin','s18'
'Benin','s19'
'Benin','s20'
'Benin','s21'
'Benin','s22'
'Bhutan','s1'
'Bhutan','s2'
'Bhutan','s3'
'Bhutan','s4'
'Bhutan','s5'
'Bhutan','s6'
'Bhutan','s7'
'Bhutan','s8'
'Bhutan','s9'
'Bhutan','s10'
'Bhutan','s11'
'Bhutan','s12'
'Bhutan','s13'
'Bhutan','s14'
'Bhutan','s15'
'Bhutan','s16'
'Bhutan','s17'
'Bhutan','s18'
'Bhutan','s19'
'Bhutan','s20'
'Bhutan','s21'
'Bhutan','s22'
'Bhutan','s23'
'Bhutan','s24'
'Bhutan','s25'
'Bhutan','s26'
'Bolivia','s1'
'Bolivia','s2'
'Bolivia','s3'
'Bolivia','s4'
'Bolivia','s5'
'Bolivia','s6'
'Bolivia','s7'
'Bolivia','s8'
'Bolivia','s9'
'Bolivia','s10'
'Bolivia','s11'
'Bolivia','s12'
'Bolivia','s13'
'Bolivia','s14'
'Bolivia','s15'
'Bolivia','s16'
'Bolivia','s17'
'Bolivia','s18'
'Bolivia','s19'
'Bolivia','s20'
'Bolivia','s21'
'Bosnia and Herzegovina','s1'
'Bosnia and Herzegovina','s2'
'Bosnia and Herzegovina','s3'
'Bosnia and Herzegovina','s4'
'Bosnia and Herzegovina','s5'
'Bosnia and Herzegovina','s6'
'Bosnia and Herzegovina','s7'
'Bosnia and Herzegovina','s8'
'Bosnia and Herzegovina','s9'
'Bosnia and Herzegovina','s10'
'Bosnia and Herzegovina','s11'
'Bosnia and Herzegovina','s12'
'Bosnia and Herzegovina','s13'
'Bosnia and Herzegovina','s14'
'Bosnia and Herzegovina','s15'
'Bosnia and Herzegovina','s16'
'Bosnia and Herzegovina','s17'
'Bosnia and Herzegovina','s18'
'Bosnia and Herzegovina','s19'
'Bosnia and Herzegovina','s20'
'Bosnia and Herzegovina','s21'
'Bosnia and Herzegovina','s22'
'Bosnia and Herzegovina','s23'
'Bosnia and Herzegovina','s24'
'Bosnia and Herzegovina','s25'
'Bosnia and Herzegovina','s26'
'Bosnia and Herzegovina','s27'
'Bosnia and Herzegovina','s28'
'Botswana','s1'
'Botswana','s2'
'Botswana','s3'
'Botswana','s4'
'Botswana','s5'
'Botswana','s6'
'Botswana','s7'
'Botswana','s8'
'Botswana','s9'
'Botswana','s10'
'Botswana','s11'
'Botswana','s12'
'Botswana','s13'
'Botswana','s14'
'Botswana','s15'
'Botswana','s16'
'Botswana','s17'
'Botswana','s18'
'Botswana','s19'
'Botswana','s20'
'Botswana','s21'
'Botswana','s22'
'Botswana','s23'
'Botswana','s24'
'Botswana','s25'
'Botswana','s26'
'Botswana','s27'
'Brazil','s1'
'Brazil','s2'
'Brazil','s3'
'Brazil','s4'
'Brazil','s5'
'Brazil','s6'
'Brazil','s7'
'Brazil','s8'
'Brazil','s9'
'Brazil','s10'
'Brazil','s11'
'Brazil','s12'
'Brazil','s13'
'Brazil','s14'
'Brazil','s15'
'Brazil','s16'
'Brazil','s17'
'Brazil','s18'
'Brazil','s19'
'Brazil','s20'
'Brazil','s21'
'Brazil','s22'
'Brazil','s23'
'Brazil','s24'
'Brazil','s25'
'Brazil','s26'
'Brazil','s27'
'Brazil','s28'
'Brazil','s29'
'Brunei','s1'
'Brunei','s2'
'Brunei','s3'
'Brunei','s4'
'Brunei','s5'
'Brunei','s6'
'Brunei','s7'
'Brunei','s8'
'Brunei','s9'
'Brunei','s10'
'Brunei','s11'
'Brunei','s12'
'Brunei','s13'
'Brunei','s14'
'Brunei','s15'
'Brunei','s16'
'Brunei','s17'
'Brunei','s18'
'Brunei','s19'
'Brunei','s20'
'Brunei','s21'
'Brunei','s22'
'Bulgaria','s1'
'Bulgaria','s2'
'Bulgaria','s3'
'Bulgaria','s4'
'Bulgaria','s5'
'Bulgaria','s6'
'Bulgaria','s7'
'Bulgaria','s8'
'Bulgaria','s9'
'Bulgaria','s10'
'Bulgaria','s11'
'Bulgaria','s12'
'Bulgaria','s13'
'Bulgaria','s14'
'Bulgaria','s15'
'Bulgaria','s16'
'Bulgaria','s17'
'Bulgaria','s18'
'Bulgaria','s19'
'Bulgaria','s20'
'Burkina Faso','s1'
'Burkina Faso','s2'
'Burkina Faso','s3'
'Burkina Faso','s4'
'Burkina Faso','s5'
'Burkina Faso','s6'
'Burkina Faso','s7'
'Burkina Faso','s8'
'Burkina Faso','s9'
'Burkina Faso','s10'
'Burkina Faso','s11'
'Burkina Faso','s12'
'Burkina Faso','s13'
'Burkina Faso','s14'
'Burkina Faso','s15'
'Burkina Faso','s16'
'Burkina Faso','s17'
'Burkina Faso','s18'
'Burkina Faso','s19'
'Burkina Faso','s20'
'Burkina Faso','s21'
'Burkina Faso','s22'
'Burundi','s1'
'Burundi','s2'
'Burundi','s3'
'Burundi','s4'
'Burundi','s5'
'Burundi','s6'
'Burundi','s7'
'Burundi','s8'
'Burundi','s9'
'Burundi','s10'
'Burundi','s11'
'Burundi','s12'
'Burundi','s13'
'Burundi','s14'
'Burundi','s15'
'Burundi','s16'
'Burundi','s17'
'Burundi','s18'
'Burundi','s19'
'Burundi','s20'
'Burundi','s21'
'Burundi','s22'
'Burundi','s23'
'Cambodia','s1'
'Cambodia','s2'
'Cambodia','s3'
'Cambodia','s4'
'Cambodia','s5'
'Cambodia','s6'
'Cambodia','s7'
'Cambodia','s8'
'Cambodia','s9'
'Cambodia','s10'
'Cambodia','s11'
'Cambodia','s12'
'Cambodia','s13'
'Cambodia','s14'
'Cambodia','s15'
'Cambodia','s16'
'Cambodia','s17'
'Cambodia','s18'
'Cambodia','s19'
'Cambodia','s20'
'Cambodia','s21'
'Cambodia','s22'
'Cambodia','s23'
'Cambodia','s24'
'Cambodia','s25'
'Cambodia','s26'
'Cambodia','s27'
'Cameroon','s1'
'Cameroon','s2'
'Cameroon','s3'
'Cameroon','s4'
'Cameroon','s5'
'Cameroon','s6'
'Cameroon','s7'
'Cameroon','s8'
'Cameroon','s9'
'Cameroon','s10'
'Cameroon','s11'
'Cameroon','s12'
'Cameroon','s13'
'Cameroon','s14'
'Cameroon','s15'
'Cameroon','s16'
'Cameroon','s17'
'Cameroon','s18'
'Cameroon','s19'
'Cameroon','s20'
'Cameroon','s21'
'Cameroon','s22'
'Cameroon','s23'
'Cameroon','s24'
'Cameroon','s25'
'Canada','s1'
'Canada','s2'
'Canada','s3'
'Canada','s4'
'Canada','s5'
'Canada','s6'
'Canada','s7'
'Canada','s8'
'Canada','s9'
'Canada','s10'
'Canada','s11'
'Canada','s12'
'Canada','s13'
'Canada','s14'
'Canada','s15'
'Canada','s16'
'Canada','s17'
'Canada','s18'
'Canada','s19'
'Canada','s20'
'Canada','s21'
'Canada','s22'
'Canada','s23'
'Canada','s24'
'Canada','s25'
'Canada','s26'
'Canada','s27'
'Canada','s28'
'Canada','s29'
'Cape Verde','s1'
'Cape Verde','s2'
'Cape Verde','s3'
'Cape Verde','s4'
'Cape Verde','s5'
'Cape Verde','s6'
'Cape Verde','s7'
'Cape Verde','s8'
'Cape Verde','s9'
'Cape Verde','s10'
'Cape Verde','s11'
'Cape Verde','s12'
'Cape Verde','s13'
'Cape Verde','s14'
'Cape Verde','s15'
'Cape Verde','s16'
'Cape Verde','s17'
'Cape Verde','s18'
'Cape Verde','s19'
'Cape Verde','s20'
'Cape Verde','s21'
'Cape Verde','s22'
'Central African Republic','s1'
'Central African Republic','s2'
'Central African Republic','s3'
'Central African Republic','s4'
'Central African Republic','s5'
'Central African Republic','s6'
'Central African Republic','s7'
'Central African Republic','s8'
'Central African Republic','s9'
'Central African Republic','s10'
'Central African Republic','s11'
'Central African Republic','s12'
'Central African Republic','s13'
'Central African Republic','s14'
'Central African Republic','s15'
'Central African Republic','s16'
'Central African Republic','s17'
'Central African Republic','s18'
'Central African Republic','s19'
'Central African Republic','s20'
'Central African Republic','s21'
'Central African Republic','s22'
'Chad','s1'
'Chad','s2'
'Chad','s3'
'Chad','s4'
'Chad','s5'
'Chad','s6'
'Chad','s7'
'Chad','s8'
'Chad','s9'
'Chad','s10'
'Chad','s11'
'Chad','s12'
'Chad','s13'
'Chad','s14'
'Chad','s15'
'Chad','s16'
'Chad','s17'
'Chad','s18'
'Chad','s19'
'Chad','s20'
'Chad','s21'
'Chad','s22'
'Chad','s23'
'Chad','s24'
'Chad','s25'
'Chad','s26'
'Chad','s27'
'Chad','s28'
'Chile','s1'
'Chile','s2'
'Chile','s3'
'Chile','s4'
'Chile','s5'
'Chile','s6'
'Chile','s7'
'Chile','s8'
'Chile','s9'
'Chile','s10'
'Chile','s11'
'Chile','s12'
'Chile','s13'
'Chile','s14'
'Chile','s15'
'Chile','s16'
'Chile','s17'
'Chile','s18'
'Chile','s19'
'Chile','s20'
'Chile','s21'
'Chile','s22'
'Chile','s23'
'Chile','s24'
'Chile','s25'
'Chile','s26'
'Chile','s27'
'Chile','s28'
'Chile','s29'
'China','s1'
'China','s2'
'China','s3'
'China','s4'
'China','s5'
'China','s6'
'China','s7'
'China','s8'
'China','s9'
'China','s10'
'China','s11'
'China','s12'
'China','s13'
'China','s14'
'China','s15'
'China','s16'
'China','s17'
'China','s18'
'China','s19'
'China','s20'
'China','s21'
'China','s22'
'China','s23'
'China','s24'
'China','s25'
'China','s26'
'China','s27'
'Colombia','s1'
'Colombia','s2'
'Colombia','s3'
'Colombia','s4'
'Colombia','s5'
'Colombia','s6'
'Colombia','s7'
'Colombia','s8'
'Colombia','s9'
'Colombia','s10'
'Colombia','s11'
'Colombia','s12'
'Colombia','s13'
'Colombia','s14'
'Colombia','s15'
'Colombia','s16'
'Colombia','s17'
'Colombia','s18'
'Colombia','s19'
'Colombia','s20'
'Colombia','s21'
'Colombia','s22'
'Colombia','s23'
'Comoros','s1'
'Comoros','s2'
'Comoros','s3'
'Comoros','s4'
'Comoros','s5'
'Comoros','s6'
'Comoros','s7'
'Comoros','s8'
'Comoros','s9'
'Comoros','s10'
'Comoros','s11'
'Comoros','s12'
'Comoros','s13'
'Comoros','s14'
'Comoros','s15'
'Comoros','s16'
'Comoros','s17'
'Comoros','s18'
'Comoros','s19'
'Comoros','s20'
'Comoros','s21'
'Comoros','s22'
'Comoros','s23'
'Comoros','s24'
'Comoros','s25'
'Comoros','s26'
'Congo','s1'
'Congo','s2'
'Congo','s3'
'Congo','s4'
'Congo','s5'
'Congo','s6'
'Congo','s7'
'Congo','s8'
'Congo','s9'
'Congo','s10'
'Congo','s11'
'Congo','s12'
'Congo','s13'
'Congo','s14'
'Congo','s15'
'Congo','s16'
'Congo','s17'
'Congo','s18'
'Congo','s19'
'Congo','s20'
'Congo','s21'
'Republic of Congo','s1'
'Republic of Congo','s2'
'Republic of Congo','s3'
'Republic of Congo','s4'
'Republic of Congo','s5'
'Republic of Congo','s6'
'Republic of Congo','s7'
'Republic of Congo','s8'
'Republic of Congo','s9'
'Republic of Congo','s10'
'Republic of Congo','s11'
'Republic of Congo','s12'
'Republic of Congo','s13'
'Republic of Congo','s14'
'Republic of Congo','s15'
'Republic of Congo','s16'
'Republic of Congo','s17'
'Republic of Congo','s18'
'Republic of Congo','s19'
'Republic of Congo','s20'
'Republic of Congo','s21'
'Republic of Congo','s22'
'Costa Rica','s1'
'Costa Rica','s2'
'Costa Rica','s3'
'Costa Rica','s4'
'Costa Rica','s5'
'Costa Rica','s6'
'Costa Rica','s7'
'Costa Rica','s8'
'Costa Rica','s9'
'Costa Rica','s10'
'Costa Rica','s11'
'Costa Rica','s12'
'Costa Rica','s13'
'Costa Rica','s14'
'Costa Rica','s15'
'Costa Rica','s16'
'Costa Rica','s17'
'Costa Rica','s18'
'Costa Rica','s19'
'Costa Rica','s20'
'Costa Rica','s21'
'Costa Rica','s22'
'Costa Rica','s23'
'Costa Rica','s24'
'Costa Rica','s25'
'Costa Rica','s26'
'Costa Rica','s27'
'Costa Rica','s28'
'Costa Rica','s29'
'Côte dIvoire','s1'
'Côte dIvoire','s2'
'Côte dIvoire','s3'
'Côte dIvoire','s4'
'Côte dIvoire','s5'
'Côte dIvoire','s6'
'Côte dIvoire','s7'
'Côte dIvoire','s8'
'Côte dIvoire','s9'
'Côte dIvoire','s10'
'Côte dIvoire','s11'
'Côte dIvoire','s12'
'Côte dIvoire','s13'
'Côte dIvoire','s14'
'Côte dIvoire','s15'
'Côte dIvoire','s16'
'Côte dIvoire','s17'
'Côte dIvoire','s18'
'Côte dIvoire','s19'
'Côte dIvoire','s20'
'Côte dIvoire','s21'
'Côte dIvoire','s22'
'Côte dIvoire','s23'
'Croatia','s1'
'Croatia','s2'
'Croatia','s3'
'Croatia','s4'
'Croatia','s5'
'Croatia','s6'
'Croatia','s7'
'Croatia','s8'
'Croatia','s9'
'Croatia','s10'
'Croatia','s11'
'Croatia','s12'
'Croatia','s13'
'Croatia','s14'
'Croatia','s15'
'Croatia','s16'
'Croatia','s17'
'Croatia','s18'
'Croatia','s19'
'Croatia','s20'
'Croatia','s21'
'Cuba','s1'
'Cuba','s2'
'Cuba','s3'
'Cuba','s4'
'Cuba','s5'
'Cuba','s6'
'Cuba','s7'
'Cuba','s8'
'Cuba','s9'
'Cuba','s10'
'Cuba','s11'
'Cuba','s12'
'Cuba','s13'
'Cuba','s14'
'Cuba','s15'
'Cuba','s16'
'Cuba','s17'
'Cuba','s18'
'Cuba','s19'
'Cuba','s20'
'Cuba','s21'
'Cuba','s22'
'Cuba','s23'
'Cuba','s24'
'Cuba','s25'
'Cuba','s26'
'Cuba','s27'
'Cuba','s28'
'Cuba','s29'
'Cyprus','s1'
'Cyprus','s2'
'Cyprus','s3'
'Cyprus','s4'
'Cyprus','s5'
'Cyprus','s6'
'Cyprus','s7'
'Cyprus','s8'
'Cyprus','s9'
'Cyprus','s10'
'Cyprus','s11'
'Cyprus','s12'
'Cyprus','s13'
'Cyprus','s14'
'Cyprus','s15'
'Cyprus','s16'
'Cyprus','s17'
'Cyprus','s18'
'Cyprus','s19'
'Cyprus','s20'
'Cyprus','s21'
'Cyprus','s22'
'Cyprus','s23'
'Cyprus','s24'
'Czech Republic','s1'
'Czech Republic','s2'
'Czech Republic','s3'
'Czech Republic','s4'
'Czech Republic','s5'
'Czech Republic','s6'
'Czech Republic','s7'
'Czech Republic','s8'
'Czech Republic','s9'
'Czech Republic','s10'
'Czech Republic','s11'
'Czech Republic','s12'
'Czech Republic','s13'
'Czech Republic','s14'
'Czech Republic','s15'
'Czech Republic','s16'
'Czech Republic','s17'
'Czech Republic','s18'
'Czech Republic','s19'
'Czech Republic','s20'
'Czech Republic','s21'
'Czech Republic','s22'
'Czech Republic','s23'
'Czech Republic','s24'
'Czech Republic','s25'
'Czech Republic','s26'
'Czech Republic','s27'
'Denmark','s1'
'Denmark','s2'
'Denmark','s3'
'Denmark','s4'
'Denmark','s5'
'Denmark','s6'
'Denmark','s7'
'Denmark','s8'
'Denmark','s9'
'Denmark','s10'
'Denmark','s11'
'Denmark','s12'
'Denmark','s13'
'Denmark','s14'
'Denmark','s15'
'Denmark','s16'
'Denmark','s17'
'Denmark','s18'
'Denmark','s19'
'Denmark','s20'
'Denmark','s21'
'Denmark','s22'
'Denmark','s23'
'Denmark','s24'
'Denmark','s25'
'Denmark','s26'
'Denmark','s27'
'Denmark','s28'
'Djibouti','s1'
'Djibouti','s2'
'Djibouti','s3'
'Djibouti','s4'
'Djibouti','s5'
'Djibouti','s6'
'Djibouti','s7'
'Djibouti','s8'
'Djibouti','s9'
'Djibouti','s10'
'Djibouti','s11'
'Djibouti','s12'
'Djibouti','s13'
'Djibouti','s14'
'Djibouti','s15'
'Djibouti','s16'
'Djibouti','s17'
'Djibouti','s18'
'Djibouti','s19'
'Djibouti','s20'
'Djibouti','s21'
'Djibouti','s22'
'Djibouti','s23'
'Djibouti','s24'
'Dominica','s1'
'Dominica','s2'
'Dominica','s3'
'Dominica','s4'
'Dominica','s5'
'Dominica','s6'
'Dominica','s7'
'Dominica','s8'
'Dominica','s9'
'Dominica','s10'
'Dominica','s11'
'Dominica','s12'
'Dominica','s13'
'Dominica','s14'
'Dominica','s15'
'Dominica','s16'
'Dominica','s17'
'Dominica','s18'
'Dominica','s19'
'Dominica','s20'
'Dominica','s21'
'Dominica','s22'
'Dominica','s23'
'Dominica','s24'
'Dominica','s25'
'Dominican Republic','s1'
'Dominican Republic','s2'
'Dominican Republic','s3'
'Dominican Republic','s4'
'Dominican Republic','s5'
'Dominican Republic','s6'
'Dominican Republic','s7'
'Dominican Republic','s8'
'Dominican Republic','s9'
'Dominican Republic','s10'
'Dominican Republic','s11'
'Dominican Republic','s12'
'Dominican Republic','s13'
'Dominican Republic','s14'
'Dominican Republic','s15'
'Dominican Republic','s16'
'Dominican Republic','s17'
'Dominican Republic','s18'
'Dominican Republic','s19'
'Dominican Republic','s20'
'East Timor','s1'
'East Timor','s2'
'East Timor','s3'
'East Timor','s4'
'East Timor','s5'
'East Timor','s6'
'East Timor','s7'
'East Timor','s8'
'East Timor','s9'
'East Timor','s10'
'East Timor','s11'
'East Timor','s12'
'East Timor','s13'
'East Timor','s14'
'East Timor','s15'
'East Timor','s16'
'East Timor','s17'
'East Timor','s18'
'East Timor','s19'
'East Timor','s20'
'East Timor','s21'
'East Timor','s22'
'East Timor','s23'
'Ecuador','s1'
'Ecuador','s2'
'Ecuador','s3'
'Ecuador','s4'
'Ecuador','s5'
'Ecuador','s6'
'Ecuador','s7'
'Ecuador','s8'
'Ecuador','s9'
'Ecuador','s10'
'Ecuador','s11'
'Ecuador','s12'
'Ecuador','s13'
'Ecuador','s14'
'Ecuador','s15'
'Ecuador','s16'
'Ecuador','s17'
'Ecuador','s18'
'Ecuador','s19'
'Ecuador','s20'
'Ecuador','s21'
'Ecuador','s22'
'Ecuador','s23'
'Ecuador','s24'
'Ecuador','s25'
'Ecuador','s26'
'Egypt','s1'
'Egypt','s2'
'Egypt','s3'
'Egypt','s4'
'Egypt','s5'
'Egypt','s6'
'Egypt','s7'
'Egypt','s8'
'Egypt','s9'
'Egypt','s10'
'Egypt','s11'
'Egypt','s12'
'Egypt','s13'
'Egypt','s14'
'Egypt','s15'
'Egypt','s16'
'Egypt','s17'
'Egypt','s18'
'Egypt','s19'
'Egypt','s20'
'Egypt','s21'
'El Salvador','s1'
'El Salvador','s2'
'El Salvador','s3'
'El Salvador','s4'
'El Salvador','s5'
'El Salvador','s6'
'El Salvador','s7'
'El Salvador','s8'
'El Salvador','s9'
'El Salvador','s10'
'El Salvador','s11'
'El Salvador','s12'
'El Salvador','s13'
'El Salvador','s14'
'El Salvador','s15'
'El Salvador','s16'
'El Salvador','s17'
'El Salvador','s18'
'El Salvador','s19'
'El Salvador','s20'
'Equatorial Guinea','s1'
'Equatorial Guinea','s2'
'Equatorial Guinea','s3'
'Equatorial Guinea','s4'
'Equatorial Guinea','s5'
'Equatorial Guinea','s6'
'Equatorial Guinea','s7'
'Equatorial Guinea','s8'
'Equatorial Guinea','s9'
'Equatorial Guinea','s10'
'Equatorial Guinea','s11'
'Equatorial Guinea','s12'
'Equatorial Guinea','s13'
'Equatorial Guinea','s14'
'Equatorial Guinea','s15'
'Equatorial Guinea','s16'
'Equatorial Guinea','s17'
'Equatorial Guinea','s18'
'Equatorial Guinea','s19'
'Equatorial Guinea','s20'
'Equatorial Guinea','s21'
'Equatorial Guinea','s22'
'Equatorial Guinea','s23'
'Equatorial Guinea','s24'
'Equatorial Guinea','s25'
'Equatorial Guinea','s26'
'Eritrea','s1'
'Eritrea','s2'
'Eritrea','s3'
'Eritrea','s4'
'Eritrea','s5'
'Eritrea','s6'
'Eritrea','s7'
'Eritrea','s8'
'Eritrea','s9'
'Eritrea','s10'
'Eritrea','s11'
'Eritrea','s12'
'Eritrea','s13'
'Eritrea','s14'
'Eritrea','s15'
'Eritrea','s16'
'Eritrea','s17'
'Eritrea','s18'
'Eritrea','s19'
'Eritrea','s20'
'Eritrea','s21'
'Eritrea','s22'
'Eritrea','s23'
'Estonia','s1'
'Estonia','s2'
'Estonia','s3'
'Estonia','s4'
'Estonia','s5'
'Estonia','s6'
'Estonia','s7'
'Estonia','s8'
'Estonia','s9'
'Estonia','s10'
'Estonia','s11'
'Estonia','s12'
'Estonia','s13'
'Estonia','s14'
'Estonia','s15'
'Estonia','s16'
'Estonia','s17'
'Estonia','s18'
'Estonia','s19'
'Estonia','s20'
'Estonia','s21'
'Estonia','s22'
'Ethiopia','s1'
'Ethiopia','s2'
'Ethiopia','s3'
'Ethiopia','s4'
'Ethiopia','s5'
'Ethiopia','s6'
'Ethiopia','s7'
'Ethiopia','s8'
'Ethiopia','s9'
'Ethiopia','s10'
'Ethiopia','s11'
'Ethiopia','s12'
'Ethiopia','s13'
'Ethiopia','s14'
'Ethiopia','s15'
'Ethiopia','s16'
'Ethiopia','s17'
'Ethiopia','s18'
'Ethiopia','s19'
'Ethiopia','s20'
'Fiji','s1'
'Fiji','s2'
'Fiji','s3'
'Fiji','s4'
'Fiji','s5'
'Fiji','s6'
'Fiji','s7'
'Fiji','s8'
'Fiji','s9'
'Fiji','s10'
'Fiji','s11'
'Fiji','s12'
'Fiji','s13'
'Fiji','s14'
'Fiji','s15'
'Fiji','s16'
'Fiji','s17'
'Fiji','s18'
'Fiji','s19'
'Fiji','s20'
'Fiji','s21'
'Fiji','s22'
'Fiji','s23'
'Fiji','s24'
'Fiji','s25'
'Fiji','s26'
'Finland','s1'
'Finland','s2'
'Finland','s3'
'Finland','s4'
'Finland','s5'
'Finland','s6'
'Finland','s7'
'Finland','s8'
'Finland','s9'
'Finland','s10'
'Finland','s11'
'Finland','s12'
'Finland','s13'
'Finland','s14'
'Finland','s15'
'Finland','s16'
'Finland','s17'
'Finland','s18'
'Finland','s19'
'Finland','s20'
'Finland','s21'
'France','s1'
'France','s2'
'France','s3'
'France','s4'
'France','s5'
'France','s6'
'France','s7'
'France','s8'
'France','s9'
'France','s10'
'France','s11'
'France','s12'
'France','s13'
'France','s14'
'France','s15'
'France','s16'
'France','s17'
'France','s18'
'France','s19'
'France','s20'
'France','s21'
'France','s22'
'France','s23'
'France','s24'
'France','s25'
'Gabon','s1'
'Gabon','s2'
'Gabon','s3'
'Gabon','s4'
'Gabon','s5'
'Gabon','s6'
'Gabon','s7'
'Gabon','s8'
'Gabon','s9'
'Gabon','s10'
'Gabon','s11'
'Gabon','s12'
'Gabon','s13'
'Gabon','s14'
'Gabon','s15'
'Gabon','s16'
'Gabon','s17'
'Gabon','s18'
'Gabon','s19'
'Gabon','s20'
'Gabon','s21'
'Gabon','s22'
'Gabon','s23'
'Gabon','s24'
'Gabon','s25'
'Gambia','s1'
'Gambia','s2'
'Gambia','s3'
'Gambia','s4'
'Gambia','s5'
'Gambia','s6'
'Gambia','s7'
'Gambia','s8'
'Gambia','s9'
'Gambia','s10'
'Gambia','s11'
'Gambia','s12'
'Gambia','s13'
'Gambia','s14'
'Gambia','s15'
'Gambia','s16'
'Gambia','s17'
'Gambia','s18'
'Gambia','s19'
'Gambia','s20'
'Gambia','s21'
'Gambia','s22'
'Gambia','s23'
'Gambia','s24'
'Georgia','s1'
'Georgia','s2'
'Georgia','s3'
'Georgia','s4'
'Georgia','s5'
'Georgia','s6'
'Georgia','s7'
'Georgia','s8'
'Georgia','s9'
'Georgia','s10'
'Georgia','s11'
'Georgia','s12'
'Georgia','s13'
'Georgia','s14'
'Georgia','s15'
'Georgia','s16'
'Georgia','s17'
'Georgia','s18'
'Georgia','s19'
'Georgia','s20'
'Georgia','s21'
'Georgia','s22'
'Georgia','s23'
'Georgia','s24'
'Georgia','s25'
'Georgia','s26'
'Georgia','s27'
'Germany','s1'
'Germany','s2'
'Germany','s3'
'Germany','s4'
'Germany','s5'
'Germany','s6'
'Germany','s7'
'Germany','s8'
'Germany','s9'
'Germany','s10'
'Germany','s11'
'Germany','s12'
'Germany','s13'
'Germany','s14'
'Germany','s15'
'Germany','s16'
'Germany','s17'
'Germany','s18'
'Germany','s19'
'Germany','s20'
'Germany','s21'
'Germany','s22'
'Germany','s23'
'Germany','s24'
'Germany','s25'
'Germany','s26'
'Ghana','s1'
'Ghana','s2'
'Ghana','s3'
'Ghana','s4'
'Ghana','s5'
'Ghana','s6'
'Ghana','s7'
'Ghana','s8'
'Ghana','s9'
'Ghana','s10'
'Ghana','s11'
'Ghana','s12'
'Ghana','s13'
'Ghana','s14'
'Ghana','s15'
'Ghana','s16'
'Ghana','s17'
'Ghana','s18'
'Ghana','s19'
'Ghana','s20'
'Ghana','s21'
'Ghana','s22'
'Ghana','s23'
'Ghana','s24'
'Ghana','s25'
'Greece','s1'
'Greece','s2'
'Greece','s3'
'Greece','s4'
'Greece','s5'
'Greece','s6'
'Greece','s7'
'Greece','s8'
'Greece','s9'
'Greece','s10'
'Greece','s11'
'Greece','s12'
'Greece','s13'
'Greece','s14'
'Greece','s15'
'Greece','s16'
'Greece','s17'
'Greece','s18'
'Greece','s19'
'Greece','s20'
'Greece','s21'
'Greece','s22'
'Greece','s23'
'Greece','s24'
'Greece','s25'
'Greece','s26'
'Grenada','s1'
'Grenada','s2'
'Grenada','s3'
'Grenada','s4'
'Grenada','s5'
'Grenada','s6'
'Grenada','s7'
'Grenada','s8'
'Grenada','s9'
'Grenada','s10'
'Grenada','s11'
'Grenada','s12'
'Grenada','s13'
'Grenada','s14'
'Grenada','s15'
'Grenada','s16'
'Grenada','s17'
'Grenada','s18'
'Grenada','s19'
'Grenada','s20'
'Grenada','s21'
'Grenada','s22'
'Grenada','s23'
'Grenada','s24'
'Grenada','s25'
'Grenada','s26'
'Grenada','s27'
'Grenada','s28'
'Grenada','s29'
'Guatemala','s1'
'Guatemala','s2'
'Guatemala','s3'
'Guatemala','s4'
'Guatemala','s5'
'Guatemala','s6'
'Guatemala','s7'
'Guatemala','s8'
'Guatemala','s9'
'Guatemala','s10'
'Guatemala','s11'
'Guatemala','s12'
'Guatemala','s13'
'Guatemala','s14'
'Guatemala','s15'
'Guatemala','s16'
'Guatemala','s17'
'Guatemala','s18'
'Guatemala','s19'
'Guatemala','s20'
'Guatemala','s21'
'Guatemala','s22'
'Guatemala','s23'
'Guinea','s1'
'Guinea','s2'
'Guinea','s3'
'Guinea','s4'
'Guinea','s5'
'Guinea','s6'
'Guinea','s7'
'Guinea','s8'
'Guinea','s9'
'Guinea','s10'
'Guinea','s11'
'Guinea','s12'
'Guinea','s13'
'Guinea','s14'
'Guinea','s15'
'Guinea','s16'
'Guinea','s17'
'Guinea','s18'
'Guinea','s19'
'Guinea','s20'
'Guinea','s21'
'Guinea','s22'
'Guinea','s23'
'Guinea','s24'
'Guinea','s25'
'Guinea','s26'
'Guinea','s27'
'Guinea-Bissau','s1'
'Guinea-Bissau','s2'
'Guinea-Bissau','s3'
'Guinea-Bissau','s4'
'Guinea-Bissau','s5'
'Guinea-Bissau','s6'
'Guinea-Bissau','s7'
'Guinea-Bissau','s8'
'Guinea-Bissau','s9'
'Guinea-Bissau','s10'
'Guinea-Bissau','s11'
'Guinea-Bissau','s12'
'Guinea-Bissau','s13'
'Guinea-Bissau','s14'
'Guinea-Bissau','s15'
'Guinea-Bissau','s16'
'Guinea-Bissau','s17'
'Guinea-Bissau','s18'
'Guinea-Bissau','s19'
'Guinea-Bissau','s20'
'Guinea-Bissau','s21'
'Guinea-Bissau','s22'
'Guinea-Bissau','s23'
'Guinea-Bissau','s24'
'Guyana','s1'
'Guyana','s2'
'Guyana','s3'
'Guyana','s4'
'Guyana','s5'
'Guyana','s6'
'Guyana','s7'
'Guyana','s8'
'Guyana','s9'
'Guyana','s10'
'Guyana','s11'
'Guyana','s12'
'Guyana','s13'
'Guyana','s14'
'Guyana','s15'
'Guyana','s16'
'Guyana','s17'
'Guyana','s18'
'Guyana','s19'
'Guyana','s20'
'Guyana','s21'
'Guyana','s22'
'Guyana','s23'
'Guyana','s24'
'Guyana','s25'
'Haiti','s1'
'Haiti','s2'
'Haiti','s3'
'Haiti','s4'
'Haiti','s5'
'Haiti','s6'
'Haiti','s7'
'Haiti','s8'
'Haiti','s9'
'Haiti','s10'
'Haiti','s11'
'Haiti','s12'
'Haiti','s13'
'Haiti','s14'
'Haiti','s15'
'Haiti','s16'
'Haiti','s17'
'Haiti','s18'
'Haiti','s19'
'Haiti','s20'
'Haiti','s21'
'Haiti','s22'
'Honduras','s1'
'Honduras','s2'
'Honduras','s3'
'Honduras','s4'
'Honduras','s5'
'Honduras','s6'
'Honduras','s7'
'Honduras','s8'
'Honduras','s9'
'Honduras','s10'
'Honduras','s11'
'Honduras','s12'
'Honduras','s13'
'Honduras','s14'
'Honduras','s15'
'Honduras','s16'
'Honduras','s17'
'Honduras','s18'
'Honduras','s19'
'Honduras','s20'
'Honduras','s21'
'Honduras','s22'
'Honduras','s23'
'Honduras','s24'
'Honduras','s25'
'Hungary','s1'
'Hungary','s2'
'Hungary','s3'
'Hungary','s4'
'Hungary','s5'
'Hungary','s6'
'Hungary','s7'
'Hungary','s8'
'Hungary','s9'
'Hungary','s10'
'Hungary','s11'
'Hungary','s12'
'Hungary','s13'
'Hungary','s14'
'Hungary','s15'
'Hungary','s16'
'Hungary','s17'
'Hungary','s18'
'Hungary','s19'
'Hungary','s20'
'Hungary','s21'
'Hungary','s22'
'Hungary','s23'
'Hungary','s24'
'Iceland','s1'
'Iceland','s2'
'Iceland','s3'
'Iceland','s4'
'Iceland','s5'
'Iceland','s6'
'Iceland','s7'
'Iceland','s8'
'Iceland','s9'
'Iceland','s10'
'Iceland','s11'
'Iceland','s12'
'Iceland','s13'
'Iceland','s14'
'Iceland','s15'
'Iceland','s16'
'Iceland','s17'
'Iceland','s18'
'Iceland','s19'
'Iceland','s20'
'Iceland','s21'
'Iceland','s22'
'Iceland','s23'
'Iceland','s24'
'Iceland','s25'
'Iceland','s26'
'Iceland','s27'
'India','s1'
'India','s2'
'India','s3'
'India','s4'
'India','s5'
'India','s6'
'India','s7'
'India','s8'
'India','s9'
'India','s10'
'India','s11'
'India','s12'
'India','s13'
'India','s14'
'India','s15'
'India','s16'
'India','s17'
'India','s18'
'India','s19'
'India','s20'
'India','s21'
'India','s22'
'India','s23'
'India','s24'
'Indonesia','s1'
'Indonesia','s2'
'Indonesia','s3'
'Indonesia','s4'
'Indonesia','s5'
'Indonesia','s6'
'Indonesia','s7'
'Indonesia','s8'
'Indonesia','s9'
'Indonesia','s10'
'Indonesia','s11'
'Indonesia','s12'
'Indonesia','s13'
'Indonesia','s14'
'Indonesia','s15'
'Indonesia','s16'
'Indonesia','s17'
'Indonesia','s18'
'Indonesia','s19'
'Indonesia','s20'
'Indonesia','s21'
'Indonesia','s22'
'Indonesia','s23'
'Indonesia','s24'
'Iran','s1'
'Iran','s2'
'Iran','s3'
'Iran','s4'
'Iran','s5'
'Iran','s6'
'Iran','s7'
'Iran','s8'
'Iran','s9'
'Iran','s10'
'Iran','s11'
'Iran','s12'
'Iran','s13'
'Iran','s14'
'Iran','s15'
'Iran','s16'
'Iran','s17'
'Iran','s18'
'Iran','s19'
'Iran','s20'
'Iran','s21'
'Iran','s22'
'Iran','s23'
'Iraq','s1'
'Iraq','s2'
'Iraq','s3'
'Iraq','s4'
'Iraq','s5'
'Iraq','s6'
'Iraq','s7'
'Iraq','s8'
'Iraq','s9'
'Iraq','s10'
'Iraq','s11'
'Iraq','s12'
'Iraq','s13'
'Iraq','s14'
'Iraq','s15'
'Iraq','s16'
'Iraq','s17'
'Iraq','s18'
'Iraq','s19'
'Iraq','s20'
'Ireland','s1'
'Ireland','s2'
'Ireland','s3'
'Ireland','s4'
'Ireland','s5'
'Ireland','s6'
'Ireland','s7'
'Ireland','s8'
'Ireland','s9'
'Ireland','s10'
'Ireland','s11'
'Ireland','s12'
'Ireland','s13'
'Ireland','s14'
'Ireland','s15'
'Ireland','s16'
'Ireland','s17'
'Ireland','s18'
'Ireland','s19'
'Ireland','s20'
'Ireland','s21'
'Ireland','s22'
'Ireland','s23'
'Ireland','s24'
'Ireland','s25'
'Ireland','s26'
'Ireland','s27'
'Israel','s1'
'Israel','s2'
'Israel','s3'
'Israel','s4'
'Israel','s5'
'Israel','s6'
'Israel','s7'
'Israel','s8'
'Israel','s9'
'Israel','s10'
'Israel','s11'
'Israel','s12'
'Israel','s13'
'Israel','s14'
'Israel','s15'
'Israel','s16'
'Israel','s17'
'Israel','s18'
'Israel','s19'
'Israel','s20'
'Israel','s21'
'Israel','s22'
'Israel','s23'
'Israel','s24'
'Israel','s25'
'Israel','s26'
'Israel','s27'
'Israel','s28'
'Italy','s1'
'Italy','s2'
'Italy','s3'
'Italy','s4'
'Italy','s5'
'Italy','s6'
'Italy','s7'
'Italy','s8'
'Italy','s9'
'Italy','s10'
'Italy','s11'
'Italy','s12'
'Italy','s13'
'Italy','s14'
'Italy','s15'
'Italy','s16'
'Italy','s17'
'Italy','s18'
'Italy','s19'
'Italy','s20'
'Italy','s21'
'Italy','s22'
'Italy','s23'
'Italy','s24'
'Italy','s25'
'Italy','s26'
'Jamaica','s1'
'Jamaica','s2'
'Jamaica','s3'
'Jamaica','s4'
'Jamaica','s5'
'Jamaica','s6'
'Jamaica','s7'
'Jamaica','s8'
'Jamaica','s9'
'Jamaica','s10'
'Jamaica','s11'
'Jamaica','s12'
'Jamaica','s13'
'Jamaica','s14'
'Jamaica','s15'
'Jamaica','s16'
'Jamaica','s17'
'Jamaica','s18'
'Jamaica','s19'
'Jamaica','s20'
'Jamaica','s21'
'Jamaica','s22'
'Jamaica','s23'
'Jamaica','s24'
'Jamaica','s25'
'Jamaica','s26'
'Jamaica','s27'
'Jamaica','s28'
'Japan','s1'
'Japan','s2'
'Japan','s3'
'Japan','s4'
'Japan','s5'
'Japan','s6'
'Japan','s7'
'Japan','s8'
'Japan','s9'
'Japan','s10'
'Japan','s11'
'Japan','s12'
'Japan','s13'
'Japan','s14'
'Japan','s15'
'Japan','s16'
'Japan','s17'
'Japan','s18'
'Japan','s19'
'Japan','s20'
'Japan','s21'
'Japan','s22'
'Japan','s23'
'Japan','s24'
'Japan','s25'
'Japan','s26'
'Japan','s27'
'Japan','s28'
'Jordan','s1'
'Jordan','s2'
'Jordan','s3'
'Jordan','s4'
'Jordan','s5'
'Jordan','s6'
'Jordan','s7'
'Jordan','s8'
'Jordan','s9'
'Jordan','s10'
'Jordan','s11'
'Jordan','s12'
'Jordan','s13'
'Jordan','s14'
'Jordan','s15'
'Jordan','s16'
'Jordan','s17'
'Jordan','s18'
'Jordan','s19'
'Jordan','s20'
'Jordan','s21'
'Jordan','s22'
'Jordan','s23'
'Jordan','s24'
'Kazakhstan','s1'
'Kazakhstan','s2'
'Kazakhstan','s3'
'Kazakhstan','s4'
'Kazakhstan','s5'
'Kazakhstan','s6'
'Kazakhstan','s7'
'Kazakhstan','s8'
'Kazakhstan','s9'
'Kazakhstan','s10'
'Kazakhstan','s11'
'Kazakhstan','s12'
'Kazakhstan','s13'
'Kazakhstan','s14'
'Kazakhstan','s15'
'Kazakhstan','s16'
'Kazakhstan','s17'
'Kazakhstan','s18'
'Kazakhstan','s19'
'Kazakhstan','s20'
'Kazakhstan','s21'
'Kazakhstan','s22'
'Kazakhstan','s23'
'Kenya','s1'
'Kenya','s2'
'Kenya','s3'
'Kenya','s4'
'Kenya','s5'
'Kenya','s6'
'Kenya','s7'
'Kenya','s8'
'Kenya','s9'
'Kenya','s10'
'Kenya','s11'
'Kenya','s12'
'Kenya','s13'
'Kenya','s14'
'Kenya','s15'
'Kenya','s16'
'Kenya','s17'
'Kenya','s18'
'Kenya','s19'
'Kenya','s20'
'Kenya','s21'
'Kiribati','s1'
'Kiribati','s2'
'Kiribati','s3'
'Kiribati','s4'
'Kiribati','s5'
'Kiribati','s6'
'Kiribati','s7'
'Kiribati','s8'
'Kiribati','s9'
'Kiribati','s10'
'Kiribati','s11'
'Kiribati','s12'
'Kiribati','s13'
'Kiribati','s14'
'Kiribati','s15'
'Kiribati','s16'
'Kiribati','s17'
'Kiribati','s18'
'Kiribati','s19'
'Kiribati','s20'
'Kiribati','s21'
'Kiribati','s22'
'Kiribati','s23'
'Kiribati','s24'
'North Korea','s1'
'North Korea','s2'
'North Korea','s3'
'North Korea','s4'
'North Korea','s5'
'North Korea','s6'
'North Korea','s7'
'North Korea','s8'
'North Korea','s9'
'North Korea','s10'
'North Korea','s11'
'North Korea','s12'
'North Korea','s13'
'North Korea','s14'
'North Korea','s15'
'North Korea','s16'
'North Korea','s17'
'North Korea','s18'
'North Korea','s19'
'North Korea','s20'
'North Korea','s21'
'North Korea','s22'
'North Korea','s23'
'North Korea','s24'
'North Korea','s25'
'North Korea','s26'
'North Korea','s27'
'North Korea','s28'
'North Korea','s29'
'South Korea','s1'
'South Korea','s2'
'South Korea','s3'
'South Korea','s4'
'South Korea','s5'
'South Korea','s6'
'South Korea','s7'
'South Korea','s8'
'South Korea','s9'
'South Korea','s10'
'South Korea','s11'
'South Korea','s12'
'South Korea','s13'
'South Korea','s14'
'South Korea','s15'
'South Korea','s16'
'South Korea','s17'
'South Korea','s18'
'South Korea','s19'
'South Korea','s20'
'South Korea','s21'
'South Korea','s22'
'Kuwait','s1'
'Kuwait','s2'
'Kuwait','s3'
'Kuwait','s4'
'Kuwait','s5'
'Kuwait','s6'
'Kuwait','s7'
'Kuwait','s8'
'Kuwait','s9'
'Kuwait','s10'
'Kuwait','s11'
'Kuwait','s12'
'Kuwait','s13'
'Kuwait','s14'
'Kuwait','s15'
'Kuwait','s16'
'Kuwait','s17'
'Kuwait','s18'
'Kuwait','s19'
'Kuwait','s20'
'Kyrgyzstan','s1'
'Kyrgyzstan','s2'
'Kyrgyzstan','s3'
'Kyrgyzstan','s4'
'Kyrgyzstan','s5'
'Kyrgyzstan','s6'
'Kyrgyzstan','s7'
'Kyrgyzstan','s8'
'Kyrgyzstan','s9'
'Kyrgyzstan','s10'
'Kyrgyzstan','s11'
'Kyrgyzstan','s12'
'Kyrgyzstan','s13'
'Kyrgyzstan','s14'
'Kyrgyzstan','s15'
'Kyrgyzstan','s16'
'Kyrgyzstan','s17'
'Kyrgyzstan','s18'
'Kyrgyzstan','s19'
'Kyrgyzstan','s20'
'Kyrgyzstan','s21'
'Kyrgyzstan','s22'
'Kyrgyzstan','s23'
'Kyrgyzstan','s24'
'Kyrgyzstan','s25'
'Kyrgyzstan','s26'
'Laos','s1'
'Laos','s2'
'Laos','s3'
'Laos','s4'
'Laos','s5'
'Laos','s6'
'Laos','s7'
'Laos','s8'
'Laos','s9'
'Laos','s10'
'Laos','s11'
'Laos','s12'
'Laos','s13'
'Laos','s14'
'Laos','s15'
'Laos','s16'
'Laos','s17'
'Laos','s18'
'Laos','s19'
'Laos','s20'
'Laos','s21'
'Laos','s22'
'Laos','s23'
'Laos','s24'
'Laos','s25'
'Laos','s26'
'Laos','s27'
'Laos','s28'
'Latvia','s1'
'Latvia','s2'
'Latvia','s3'
'Latvia','s4'
'Latvia','s5'
'Latvia','s6'
'Latvia','s7'
'Latvia','s8'
'Latvia','s9'
'Latvia','s10'
'Latvia','s11'
'Latvia','s12'
'Latvia','s13'
'Latvia','s14'
'Latvia','s15'
'Latvia','s16'
'Latvia','s17'
'Latvia','s18'
'Latvia','s19'
'Latvia','s20'
'Latvia','s21'
'Latvia','s22'
'Latvia','s23'
'Latvia','s24'
'Latvia','s25'
'Latvia','s26'
'Latvia','s27'
'Latvia','s28'
'Latvia','s29'
'Lebanon','s1'
'Lebanon','s2'
'Lebanon','s3'
'Lebanon','s4'
'Lebanon','s5'
'Lebanon','s6'
'Lebanon','s7'
'Lebanon','s8'
'Lebanon','s9'
'Lebanon','s10'
'Lebanon','s11'
'Lebanon','s12'
'Lebanon','s13'
'Lebanon','s14'
'Lebanon','s15'
'Lebanon','s16'
'Lebanon','s17'
'Lebanon','s18'
'Lebanon','s19'
'Lebanon','s20'
'Lebanon','s21'
'Lebanon','s22'
'Lesotho','s1'
'Lesotho','s2'
'Lesotho','s3'
'Lesotho','s4'
'Lesotho','s5'
'Lesotho','s6'
'Lesotho','s7'
'Lesotho','s8'
'Lesotho','s9'
'Lesotho','s10'
'Lesotho','s11'
'Lesotho','s12'
'Lesotho','s13'
'Lesotho','s14'
'Lesotho','s15'
'Lesotho','s16'
'Lesotho','s17'
'Lesotho','s18'
'Lesotho','s19'
'Lesotho','s20'
'Lesotho','s21'
'Lesotho','s22'
'Lesotho','s23'
'Lesotho','s24'
'Lesotho','s25'
'Lesotho','s26'
'Liberia','s1'
'Liberia','s2'
'Liberia','s3'
'Liberia','s4'
'Liberia','s5'
'Liberia','s6'
'Liberia','s7'
'Liberia','s8'
'Liberia','s9'
'Liberia','s10'
'Liberia','s11'
'Liberia','s12'
'Liberia','s13'
'Liberia','s14'
'Liberia','s15'
'Liberia','s16'
'Liberia','s17'
'Liberia','s18'
'Liberia','s19'
'Liberia','s20'
'Liberia','s21'
'Liberia','s22'
'Liberia','s23'
'Liberia','s24'
'Liberia','s25'
'Liberia','s26'
'Libya','s1'
'Libya','s2'
'Libya','s3'
'Libya','s4'
'Libya','s5'
'Libya','s6'
'Libya','s7'
'Libya','s8'
'Libya','s9'
'Libya','s10'
'Libya','s11'
'Libya','s12'
'Libya','s13'
'Libya','s14'
'Libya','s15'
'Libya','s16'
'Libya','s17'
'Libya','s18'
'Libya','s19'
'Libya','s20'
'Libya','s21'
'Libya','s22'
'Libya','s23'
'Libya','s24'
'Liechtenstein','s1'
'Liechtenstein','s2'
'Liechtenstein','s3'
'Liechtenstein','s4'
'Liechtenstein','s5'
'Liechtenstein','s6'
'Liechtenstein','s7'
'Liechtenstein','s8'
'Liechtenstein','s9'
'Liechtenstein','s10'
'Liechtenstein','s11'
'Liechtenstein','s12'
'Liechtenstein','s13'
'Liechtenstein','s14'
'Liechtenstein','s15'
'Liechtenstein','s16'
'Liechtenstein','s17'
'Liechtenstein','s18'
'Liechtenstein','s19'
'Liechtenstein','s20'
'Liechtenstein','s21'
'Liechtenstein','s22'
'Liechtenstein','s23'
'Liechtenstein','s24'
'Liechtenstein','s25'
'Liechtenstein','s26'
'Liechtenstein','s27'
'Liechtenstein','s28'
'Liechtenstein','s29'
'Lithuania','s1'
'Lithuania','s2'
'Lithuania','s3'
'Lithuania','s4'
'Lithuania','s5'
'Lithuania','s6'
'Lithuania','s7'
'Lithuania','s8'
'Lithuania','s9'
'Lithuania','s10'
'Lithuania','s11'
'Lithuania','s12'
'Lithuania','s13'
'Lithuania','s14'
'Lithuania','s15'
'Lithuania','s16'
'Lithuania','s17'
'Lithuania','s18'
'Lithuania','s19'
'Lithuania','s20'
'Lithuania','s21'
'Lithuania','s22'
'Lithuania','s23'
'Lithuania','s24'
'Lithuania','s25'
'Luxembourg','s1'
'Luxembourg','s2'
'Luxembourg','s3'
'Luxembourg','s4'
'Luxembourg','s5'
'Luxembourg','s6'
'Luxembourg','s7'
'Luxembourg','s8'
'Luxembourg','s9'
'Luxembourg','s10'
'Luxembourg','s11'
'Luxembourg','s12'
'Luxembourg','s13'
'Luxembourg','s14'
'Luxembourg','s15'
'Luxembourg','s16'
'Luxembourg','s17'
'Luxembourg','s18'
'Luxembourg','s19'
'Luxembourg','s20'
'Macedonia','s1'
'Macedonia','s2'
'Macedonia','s3'
'Macedonia','s4'
'Macedonia','s5'
'Macedonia','s6'
'Macedonia','s7'
'Macedonia','s8'
'Macedonia','s9'
'Macedonia','s10'
'Macedonia','s11'
'Macedonia','s12'
'Macedonia','s13'
'Macedonia','s14'
'Macedonia','s15'
'Macedonia','s16'
'Macedonia','s17'
'Macedonia','s18'
'Macedonia','s19'
'Macedonia','s20'
'Macedonia','s21'
'Macedonia','s22'
'Macedonia','s23'
'Macedonia','s24'
'Madagascar','s1'
'Madagascar','s2'
'Madagascar','s3'
'Madagascar','s4'
'Madagascar','s5'
'Madagascar','s6'
'Madagascar','s7'
'Madagascar','s8'
'Madagascar','s9'
'Madagascar','s10'
'Madagascar','s11'
'Madagascar','s12'
'Madagascar','s13'
'Madagascar','s14'
'Madagascar','s15'
'Madagascar','s16'
'Madagascar','s17'
'Madagascar','s18'
'Madagascar','s19'
'Madagascar','s20'
'Madagascar','s21'
'Madagascar','s22'
'Madagascar','s23'
'Madagascar','s24'
'Madagascar','s25'
'Madagascar','s26'
'Madagascar','s27'
'Madagascar','s28'
'Malawi','s1'
'Malawi','s2'
'Malawi','s3'
'Malawi','s4'
'Malawi','s5'
'Malawi','s6'
'Malawi','s7'
'Malawi','s8'
'Malawi','s9'
'Malawi','s10'
'Malawi','s11'
'Malawi','s12'
'Malawi','s13'
'Malawi','s14'
'Malawi','s15'
'Malawi','s16'
'Malawi','s17'
'Malawi','s18'
'Malawi','s19'
'Malawi','s20'
'Malawi','s21'
'Malawi','s22'
'Malawi','s23'
'Malawi','s24'
'Malawi','s25'
'Malawi','s26'
'Malawi','s27'
'Malaysia','s1'
'Malaysia','s2'
'Malaysia','s3'
'Malaysia','s4'
'Malaysia','s5'
'Malaysia','s6'
'Malaysia','s7'
'Malaysia','s8'
'Malaysia','s9'
'Malaysia','s10'
'Malaysia','s11'
'Malaysia','s12'
'Malaysia','s13'
'Malaysia','s14'
'Malaysia','s15'
'Malaysia','s16'
'Malaysia','s17'
'Malaysia','s18'
'Malaysia','s19'
'Malaysia','s20'
'Malaysia','s21'
'Maldives','s1'
'Maldives','s2'
'Maldives','s3'
'Maldives','s4'
'Maldives','s5'
'Maldives','s6'
'Maldives','s7'
'Maldives','s8'
'Maldives','s9'
'Maldives','s10'
'Maldives','s11'
'Maldives','s12'
'Maldives','s13'
'Maldives','s14'
'Maldives','s15'
'Maldives','s16'
'Maldives','s17'
'Maldives','s18'
'Maldives','s19'
'Maldives','s20'
'Maldives','s21'
'Maldives','s22'
'Maldives','s23'
'Maldives','s24'
'Maldives','s25'
'Maldives','s26'
'Maldives','s27'
'Mali','s1'
'Mali','s2'
'Mali','s3'
'Mali','s4'
'Mali','s5'
'Mali','s6'
'Mali','s7'
'Mali','s8'
'Mali','s9'
'Mali','s10'
'Mali','s11'
'Mali','s12'
'Mali','s13'
'Mali','s14'
'Mali','s15'
'Mali','s16'
'Mali','s17'
'Mali','s18'
'Mali','s19'
'Mali','s20'
'Mali','s21'
'Mali','s22'
'Malta','s1'
'Malta','s2'
'Malta','s3'
'Malta','s4'
'Malta','s5'
'Malta','s6'
'Malta','s7'
'Malta','s8'
'Malta','s9'
'Malta','s10'
'Malta','s11'
'Malta','s12'
'Malta','s13'
'Malta','s14'
'Malta','s15'
'Malta','s16'
'Malta','s17'
'Malta','s18'
'Malta','s19'
'Malta','s20'
'Malta','s21'
'Malta','s22'
'Malta','s23'
'Malta','s24'
'Malta','s25'
'Malta','s26'
'Malta','s27'
'Mauritania','s1'
'Mauritania','s2'
'Mauritania','s3'
'Mauritania','s4'
'Mauritania','s5'
'Mauritania','s6'
'Mauritania','s7'
'Mauritania','s8'
'Mauritania','s9'
'Mauritania','s10'
'Mauritania','s11'
'Mauritania','s12'
'Mauritania','s13'
'Mauritania','s14'
'Mauritania','s15'
'Mauritania','s16'
'Mauritania','s17'
'Mauritania','s18'
'Mauritania','s19'
'Mauritania','s20'
'Mauritania','s21'
'Mauritania','s22'
'Mauritius','s1'
'Mauritius','s2'
'Mauritius','s3'
'Mauritius','s4'
'Mauritius','s5'
'Mauritius','s6'
'Mauritius','s7'
'Mauritius','s8'
'Mauritius','s9'
'Mauritius','s10'
'Mauritius','s11'
'Mauritius','s12'
'Mauritius','s13'
'Mauritius','s14'
'Mauritius','s15'
'Mauritius','s16'
'Mauritius','s17'
'Mauritius','s18'
'Mauritius','s19'
'Mauritius','s20'
'Mauritius','s21'
'Mauritius','s22'
'Mexico','s1'
'Mexico','s2'
'Mexico','s3'
'Mexico','s4'
'Mexico','s5'
'Mexico','s6'
'Mexico','s7'
'Mexico','s8'
'Mexico','s9'
'Mexico','s10'
'Mexico','s11'
'Mexico','s12'
'Mexico','s13'
'Mexico','s14'
'Mexico','s15'
'Mexico','s16'
'Mexico','s17'
'Mexico','s18'
'Mexico','s19'
'Mexico','s20'
'Mexico','s21'
'Mexico','s22'
'Mexico','s23'
'Mexico','s24'
'Mexico','s25'
'Mexico','s26'
'Moldova','s1'
'Moldova','s2'
'Moldova','s3'
'Moldova','s4'
'Moldova','s5'
'Moldova','s6'
'Moldova','s7'
'Moldova','s8'
'Moldova','s9'
'Moldova','s10'
'Moldova','s11'
'Moldova','s12'
'Moldova','s13'
'Moldova','s14'
'Moldova','s15'
'Moldova','s16'
'Moldova','s17'
'Moldova','s18'
'Moldova','s19'
'Moldova','s20'
'Moldova','s21'
'Monaco','s1'
'Monaco','s2'
'Monaco','s3'
'Monaco','s4'
'Monaco','s5'
'Monaco','s6'
'Monaco','s7'
'Monaco','s8'
'Monaco','s9'
'Monaco','s10'
'Monaco','s11'
'Monaco','s12'
'Monaco','s13'
'Monaco','s14'
'Monaco','s15'
'Monaco','s16'
'Monaco','s17'
'Monaco','s18'
'Monaco','s19'
'Monaco','s20'
'Mongolia','s1'
'Mongolia','s2'
'Mongolia','s3'
'Mongolia','s4'
'Mongolia','s5'
'Mongolia','s6'
'Mongolia','s7'
'Mongolia','s8'
'Mongolia','s9'
'Mongolia','s10'
'Mongolia','s11'
'Mongolia','s12'
'Mongolia','s13'
'Mongolia','s14'
'Mongolia','s15'
'Mongolia','s16'
'Mongolia','s17'
'Mongolia','s18'
'Mongolia','s19'
'Mongolia','s20'
'Mongolia','s21'
'Mongolia','s22'
'Mongolia','s23'
'Mongolia','s24'
'Mongolia','s25'
'Mongolia','s26'
'Montenegro','s1'
'Montenegro','s2'
'Montenegro','s3'
'Montenegro','s4'
'Montenegro','s5'
'Montenegro','s6'
'Montenegro','s7'
'Montenegro','s8'
'Montenegro','s9'
'Montenegro','s10'
'Montenegro','s11'
'Montenegro','s12'
'Montenegro','s13'
'Montenegro','s14'
'Montenegro','s15'
'Montenegro','s16'
'Montenegro','s17'
'Montenegro','s18'
'Montenegro','s19'
'Montenegro','s20'
'Montenegro','s21'
'Morocco','s1'
'Morocco','s2'
'Morocco','s3'
'Morocco','s4'
'Morocco','s5'
'Morocco','s6'
'Morocco','s7'
'Morocco','s8'
'Morocco','s9'
'Morocco','s10'
'Morocco','s11'
'Morocco','s12'
'Morocco','s13'
'Morocco','s14'
'Morocco','s15'
'Morocco','s16'
'Morocco','s17'
'Morocco','s18'
'Morocco','s19'
'Morocco','s20'
'Morocco','s21'
'Morocco','s22'
'Morocco','s23'
'Morocco','s24'
'Morocco','s25'
'Mozambique','s1'
'Mozambique','s2'
'Mozambique','s3'
'Mozambique','s4'
'Mozambique','s5'
'Mozambique','s6'
'Mozambique','s7'
'Mozambique','s8'
'Mozambique','s9'
'Mozambique','s10'
'Mozambique','s11'
'Mozambique','s12'
'Mozambique','s13'
'Mozambique','s14'
'Mozambique','s15'
'Mozambique','s16'
'Mozambique','s17'
'Mozambique','s18'
'Mozambique','s19'
'Mozambique','s20'
'Mozambique','s21'
'Mozambique','s22'
'Mozambique','s23'
'Mozambique','s24'
'Mozambique','s25'
'Mozambique','s26'
'Mozambique','s27'
'Mozambique','s28'
'Mozambique','s29'
'Myanmar','s1'
'Myanmar','s2'
'Myanmar','s3'
'Myanmar','s4'
'Myanmar','s5'
'Myanmar','s6'
'Myanmar','s7'
'Myanmar','s8'
'Myanmar','s9'
'Myanmar','s10'
'Myanmar','s11'
'Myanmar','s12'
'Myanmar','s13'
'Myanmar','s14'
'Myanmar','s15'
'Myanmar','s16'
'Myanmar','s17'
'Myanmar','s18'
'Myanmar','s19'
'Myanmar','s20'
'Myanmar','s21'
'Myanmar','s22'
'Myanmar','s23'
'Myanmar','s24'
'Namibia','s1'
'Namibia','s2'
'Namibia','s3'
'Namibia','s4'
'Namibia','s5'
'Namibia','s6'
'Namibia','s7'
'Namibia','s8'
'Namibia','s9'
'Namibia','s10'
'Namibia','s11'
'Namibia','s12'
'Namibia','s13'
'Namibia','s14'
'Namibia','s15'
'Namibia','s16'
'Namibia','s17'
'Namibia','s18'
'Namibia','s19'
'Namibia','s20'
'Namibia','s21'
'Namibia','s22'
'Namibia','s23'
'Namibia','s24'
'Namibia','s25'
'Namibia','s26'
'Namibia','s27'
'Namibia','s28'
'Namibia','s29'
'Nauru','s1'
'Nauru','s2'
'Nauru','s3'
'Nauru','s4'
'Nauru','s5'
'Nauru','s6'
'Nauru','s7'
'Nauru','s8'
'Nauru','s9'
'Nauru','s10'
'Nauru','s11'
'Nauru','s12'
'Nauru','s13'
'Nauru','s14'
'Nauru','s15'
'Nauru','s16'
'Nauru','s17'
'Nauru','s18'
'Nauru','s19'
'Nauru','s20'
'Nepal','s1'
'Nepal','s2'
'Nepal','s3'
'Nepal','s4'
'Nepal','s5'
'Nepal','s6'
'Nepal','s7'
'Nepal','s8'
'Nepal','s9'
'Nepal','s10'
'Nepal','s11'
'Nepal','s12'
'Nepal','s13'
'Nepal','s14'
'Nepal','s15'
'Nepal','s16'
'Nepal','s17'
'Nepal','s18'
'Nepal','s19'
'Nepal','s20'
'Nepal','s21'
'Nepal','s22'
'Nepal','s23'
'Nepal','s24'
'Nepal','s25'
'Nepal','s26'
'Nepal','s27'
'Nepal','s28'
'Nepal','s29'
'Netherlands','s1'
'Netherlands','s2'
'Netherlands','s3'
'Netherlands','s4'
'Netherlands','s5'
'Netherlands','s6'
'Netherlands','s7'
'Netherlands','s8'
'Netherlands','s9'
'Netherlands','s10'
'Netherlands','s11'
'Netherlands','s12'
'Netherlands','s13'
'Netherlands','s14'
'Netherlands','s15'
'Netherlands','s16'
'Netherlands','s17'
'Netherlands','s18'
'Netherlands','s19'
'Netherlands','s20'
'Netherlands','s21'
'New Zealand','s1'
'New Zealand','s2'
'New Zealand','s3'
'New Zealand','s4'
'New Zealand','s5'
'New Zealand','s6'
'New Zealand','s7'
'New Zealand','s8'
'New Zealand','s9'
'New Zealand','s10'
'New Zealand','s11'
'New Zealand','s12'
'New Zealand','s13'
'New Zealand','s14'
'New Zealand','s15'
'New Zealand','s16'
'New Zealand','s17'
'New Zealand','s18'
'New Zealand','s19'
'New Zealand','s20'
'New Zealand','s21'
'New Zealand','s22'
'New Zealand','s23'
'New Zealand','s24'
'New Zealand','s25'
'New Zealand','s26'
'New Zealand','s27'
'Nicaragua','s1'
'Nicaragua','s2'
'Nicaragua','s3'
'Nicaragua','s4'
'Nicaragua','s5'
'Nicaragua','s6'
'Nicaragua','s7'
'Nicaragua','s8'
'Nicaragua','s9'
'Nicaragua','s10'
'Nicaragua','s11'
'Nicaragua','s12'
'Nicaragua','s13'
'Nicaragua','s14'
'Nicaragua','s15'
'Nicaragua','s16'
'Nicaragua','s17'
'Nicaragua','s18'
'Nicaragua','s19'
'Nicaragua','s20'
'Nicaragua','s21'
'Nicaragua','s22'
'Nicaragua','s23'
'Nicaragua','s24'
'Nicaragua','s25'
'Nicaragua','s26'
'Nicaragua','s27'
'Niger','s1'
'Niger','s2'
'Niger','s3'
'Niger','s4'
'Niger','s5'
'Niger','s6'
'Niger','s7'
'Niger','s8'
'Niger','s9'
'Niger','s10'
'Niger','s11'
'Niger','s12'
'Niger','s13'
'Niger','s14'
'Niger','s15'
'Niger','s16'
'Niger','s17'
'Niger','s18'
'Niger','s19'
'Niger','s20'
'Niger','s21'
'Nigeria','s1'
'Nigeria','s2'
'Nigeria','s3'
'Nigeria','s4'
'Nigeria','s5'
'Nigeria','s6'
'Nigeria','s7'
'Nigeria','s8'
'Nigeria','s9'
'Nigeria','s10'
'Nigeria','s11'
'Nigeria','s12'
'Nigeria','s13'
'Nigeria','s14'
'Nigeria','s15'
'Nigeria','s16'
'Nigeria','s17'
'Nigeria','s18'
'Nigeria','s19'
'Nigeria','s20'
'Nigeria','s21'
'Norway','s1'
'Norway','s2'
'Norway','s3'
'Norway','s4'
'Norway','s5'
'Norway','s6'
'Norway','s7'
'Norway','s8'
'Norway','s9'
'Norway','s10'
'Norway','s11'
'Norway','s12'
'Norway','s13'
'Norway','s14'
'Norway','s15'
'Norway','s16'
'Norway','s17'
'Norway','s18'
'Norway','s19'
'Norway','s20'
'Norway','s21'
'Norway','s22'
'Norway','s23'
'Norway','s24'
'Norway','s25'
'Oman','s1'
'Oman','s2'
'Oman','s3'
'Oman','s4'
'Oman','s5'
'Oman','s6'
'Oman','s7'
'Oman','s8'
'Oman','s9'
'Oman','s10'
'Oman','s11'
'Oman','s12'
'Oman','s13'
'Oman','s14'
'Oman','s15'
'Oman','s16'
'Oman','s17'
'Oman','s18'
'Oman','s19'
'Oman','s20'
'Oman','s21'
'Oman','s22'
'Oman','s23'
'Oman','s24'
'Oman','s25'
'Oman','s26'
'Oman','s27'
'Oman','s28'
'Oman','s29'
'Pakistan','s1'
'Pakistan','s2'
'Pakistan','s3'
'Pakistan','s4'
'Pakistan','s5'
'Pakistan','s6'
'Pakistan','s7'
'Pakistan','s8'
'Pakistan','s9'
'Pakistan','s10'
'Pakistan','s11'
'Pakistan','s12'
'Pakistan','s13'
'Pakistan','s14'
'Pakistan','s15'
'Pakistan','s16'
'Pakistan','s17'
'Pakistan','s18'
'Pakistan','s19'
'Pakistan','s20'
'Pakistan','s21'
'Pakistan','s22'
'Pakistan','s23'
'Pakistan','s24'
'Pakistan','s25'
'Pakistan','s26'
'Pakistan','s27'
'Palau','s1'
'Palau','s2'
'Palau','s3'
'Palau','s4'
'Palau','s5'
'Palau','s6'
'Palau','s7'
'Palau','s8'
'Palau','s9'
'Palau','s10'
'Palau','s11'
'Palau','s12'
'Palau','s13'
'Palau','s14'
'Palau','s15'
'Palau','s16'
'Palau','s17'
'Palau','s18'
'Palau','s19'
'Palau','s20'
'Palau','s21'
'Palau','s22'
'Palau','s23'
'Palau','s24'
'Palau','s25'
'Palau','s26'
'Palau','s27'
'Palestinian State','s1'
'Palestinian State','s2'
'Palestinian State','s3'
'Palestinian State','s4'
'Palestinian State','s5'
'Palestinian State','s6'
'Palestinian State','s7'
'Palestinian State','s8'
'Palestinian State','s9'
'Palestinian State','s10'
'Palestinian State','s11'
'Palestinian State','s12'
'Palestinian State','s13'
'Palestinian State','s14'
'Palestinian State','s15'
'Palestinian State','s16'
'Palestinian State','s17'
'Palestinian State','s18'
'Palestinian State','s19'
'Palestinian State','s20'
'Palestinian State','s21'
'Palestinian State','s22'
'Palestinian State','s23'
'Palestinian State','s24'
'Palestinian State','s25'
'Palestinian State','s26'
'Panama balboa','s1'
'Panama balboa','s2'
'Panama balboa','s3'
'Panama balboa','s4'
'Panama balboa','s5'
'Panama balboa','s6'
'Panama balboa','s7'
'Panama balboa','s8'
'Panama balboa','s9'
'Panama balboa','s10'
'Panama balboa','s11'
'Panama balboa','s12'
'Panama balboa','s13'
'Panama balboa','s14'
'Panama balboa','s15'
'Panama balboa','s16'
'Panama balboa','s17'
'Panama balboa','s18'
'Panama balboa','s19'
'Panama balboa','s20'
'Panama balboa','s21'
'Panama balboa','s22'
'Panama balboa','s23'
'Panama balboa','s24'
'Panama balboa','s25'
'Panama balboa','s26'
'Panama balboa','s27'
'Papua New Guinea','s1'
'Papua New Guinea','s2'
'Papua New Guinea','s3'
'Papua New Guinea','s4'
'Papua New Guinea','s5'
'Papua New Guinea','s6'
'Papua New Guinea','s7'
'Papua New Guinea','s8'
'Papua New Guinea','s9'
'Papua New Guinea','s10'
'Papua New Guinea','s11'
'Papua New Guinea','s12'
'Papua New Guinea','s13'
'Papua New Guinea','s14'
'Papua New Guinea','s15'
'Papua New Guinea','s16'
'Papua New Guinea','s17'
'Papua New Guinea','s18'
'Papua New Guinea','s19'
'Papua New Guinea','s20'
'Papua New Guinea','s21'
'Papua New Guinea','s22'
'Papua New Guinea','s23'
'Paraguay','s1'
'Paraguay','s2'
'Paraguay','s3'
'Paraguay','s4'
'Paraguay','s5'
'Paraguay','s6'
'Paraguay','s7'
'Paraguay','s8'
'Paraguay','s9'
'Paraguay','s10'
'Paraguay','s11'
'Paraguay','s12'
'Paraguay','s13'
'Paraguay','s14'
'Paraguay','s15'
'Paraguay','s16'
'Paraguay','s17'
'Paraguay','s18'
'Paraguay','s19'
'Paraguay','s20'
'Paraguay','s21'
'Paraguay','s22'
'Paraguay','s23'
'Paraguay','s24'
'Paraguay','s25'
'Paraguay','s26'
'Peru','s1'
'Peru','s2'
'Peru','s3'
'Peru','s4'
'Peru','s5'
'Peru','s6'
'Peru','s7'
'Peru','s8'
'Peru','s9'
'Peru','s10'
'Peru','s11'
'Peru','s12'
'Peru','s13'
'Peru','s14'
'Peru','s15'
'Peru','s16'
'Peru','s17'
'Peru','s18'
'Peru','s19'
'Peru','s20'
'Peru','s21'
'Peru','s22'
'Peru','s23'
'Peru','s24'
'Peru','s25'
'Philippines','s1'
'Philippines','s2'
'Philippines','s3'
'Philippines','s4'
'Philippines','s5'
'Philippines','s6'
'Philippines','s7'
'Philippines','s8'
'Philippines','s9'
'Philippines','s10'
'Philippines','s11'
'Philippines','s12'
'Philippines','s13'
'Philippines','s14'
'Philippines','s15'
'Philippines','s16'
'Philippines','s17'
'Philippines','s18'
'Philippines','s19'
'Philippines','s20'
'Philippines','s21'
'Philippines','s22'
'Philippines','s23'
'Philippines','s24'
'Philippines','s25'
'Philippines','s26'
'Poland','s1'
'Poland','s2'
'Poland','s3'
'Poland','s4'
'Poland','s5'
'Poland','s6'
'Poland','s7'
'Poland','s8'
'Poland','s9'
'Poland','s10'
'Poland','s11'
'Poland','s12'
'Poland','s13'
'Poland','s14'
'Poland','s15'
'Poland','s16'
'Poland','s17'
'Poland','s18'
'Poland','s19'
'Poland','s20'
'Poland','s21'
'Poland','s22'
'Poland','s23'
'Portugal','s1'
'Portugal','s2'
'Portugal','s3'
'Portugal','s4'
'Portugal','s5'
'Portugal','s6'
'Portugal','s7'
'Portugal','s8'
'Portugal','s9'
'Portugal','s10'
'Portugal','s11'
'Portugal','s12'
'Portugal','s13'
'Portugal','s14'
'Portugal','s15'
'Portugal','s16'
'Portugal','s17'
'Portugal','s18'
'Portugal','s19'
'Portugal','s20'
'Portugal','s21'
'Portugal','s22'
'Portugal','s23'
'Portugal','s24'
'Portugal','s25'
'Portugal','s26'
'Portugal','s27'
'Portugal','s28'
'Portugal','s29'
'Qatar','s1'
'Qatar','s2'
'Qatar','s3'
'Qatar','s4'
'Qatar','s5'
'Qatar','s6'
'Qatar','s7'
'Qatar','s8'
'Qatar','s9'
'Qatar','s10'
'Qatar','s11'
'Qatar','s12'
'Qatar','s13'
'Qatar','s14'
'Qatar','s15'
'Qatar','s16'
'Qatar','s17'
'Qatar','s18'
'Qatar','s19'
'Qatar','s20'
'Qatar','s21'
'Qatar','s22'
'Qatar','s23'
'Qatar','s24'
'Romania','s1'
'Romania','s2'
'Romania','s3'
'Romania','s4'
'Romania','s5'
'Romania','s6'
'Romania','s7'
'Romania','s8'
'Romania','s9'
'Romania','s10'
'Romania','s11'
'Romania','s12'
'Romania','s13'
'Romania','s14'
'Romania','s15'
'Romania','s16'
'Romania','s17'
'Romania','s18'
'Romania','s19'
'Romania','s20'
'Romania','s21'
'Romania','s22'
'Romania','s23'
'Romania','s24'
'Romania','s25'
'Romania','s26'
'Romania','s27'
'Romania','s28'
'Russia','s1'
'Russia','s2'
'Russia','s3'
'Russia','s4'
'Russia','s5'
'Russia','s6'
'Russia','s7'
'Russia','s8'
'Russia','s9'
'Russia','s10'
'Russia','s11'
'Russia','s12'
'Russia','s13'
'Russia','s14'
'Russia','s15'
'Russia','s16'
'Russia','s17'
'Russia','s18'
'Russia','s19'
'Russia','s20'
'Russia','s21'
'Rwanda','s1'
'Rwanda','s2'
'Rwanda','s3'
'Rwanda','s4'
'Rwanda','s5'
'Rwanda','s6'
'Rwanda','s7'
'Rwanda','s8'
'Rwanda','s9'
'Rwanda','s10'
'Rwanda','s11'
'Rwanda','s12'
'Rwanda','s13'
'Rwanda','s14'
'Rwanda','s15'
'Rwanda','s16'
'Rwanda','s17'
'Rwanda','s18'
'Rwanda','s19'
'Rwanda','s20'
'Rwanda','s21'
'Rwanda','s22'
'St. Kitts and Nevis','s1'
'St. Kitts and Nevis','s2'
'St. Kitts and Nevis','s3'
'St. Kitts and Nevis','s4'
'St. Kitts and Nevis','s5'
'St. Kitts and Nevis','s6'
'St. Kitts and Nevis','s7'
'St. Kitts and Nevis','s8'
'St. Kitts and Nevis','s9'
'St. Kitts and Nevis','s10'
'St. Kitts and Nevis','s11'
'St. Kitts and Nevis','s12'
'St. Kitts and Nevis','s13'
'St. Kitts and Nevis','s14'
'St. Kitts and Nevis','s15'
'St. Kitts and Nevis','s16'
'St. Kitts and Nevis','s17'
'St. Kitts and Nevis','s18'
'St. Kitts and Nevis','s19'
'St. Kitts and Nevis','s20'
'St. Kitts and Nevis','s21'
'St. Kitts and Nevis','s22'
'St. Kitts and Nevis','s23'
'St. Kitts and Nevis','s24'
'St. Kitts and Nevis','s25'
'St. Kitts and Nevis','s26'
'St. Kitts and Nevis','s27'
'St. Kitts and Nevis','s28'
'St. Kitts and Nevis','s29'
'St. Lucia','s1'
'St. Lucia','s2'
'St. Lucia','s3'
'St. Lucia','s4'
'St. Lucia','s5'
'St. Lucia','s6'
'St. Lucia','s7'
'St. Lucia','s8'
'St. Lucia','s9'
'St. Lucia','s10'
'St. Lucia','s11'
'St. Lucia','s12'
'St. Lucia','s13'
'St. Lucia','s14'
'St. Lucia','s15'
'St. Lucia','s16'
'St. Lucia','s17'
'St. Lucia','s18'
'St. Lucia','s19'
'St. Lucia','s20'
'St. Lucia','s21'
'St. Lucia','s22'
'St. Lucia','s23'
'St. Vincent and the Grenadines','s1'
'St. Vincent and the Grenadines','s2'
'St. Vincent and the Grenadines','s3'
'St. Vincent and the Grenadines','s4'
'St. Vincent and the Grenadines','s5'
'St. Vincent and the Grenadines','s6'
'St. Vincent and the Grenadines','s7'
'St. Vincent and the Grenadines','s8'
'St. Vincent and the Grenadines','s9'
'St. Vincent and the Grenadines','s10'
'St. Vincent and the Grenadines','s11'
'St. Vincent and the Grenadines','s12'
'St. Vincent and the Grenadines','s13'
'St. Vincent and the Grenadines','s14'
'St. Vincent and the Grenadines','s15'
'St. Vincent and the Grenadines','s16'
'St. Vincent and the Grenadines','s17'
'St. Vincent and the Grenadines','s18'
'St. Vincent and the Grenadines','s19'
'St. Vincent and the Grenadines','s20'
'St. Vincent and the Grenadines','s21'
'St. Vincent and the Grenadines','s22'
'St. Vincent and the Grenadines','s23'
'St. Vincent and the Grenadines','s24'
'St. Vincent and the Grenadines','s25'
'St. Vincent and the Grenadines','s26'
'St. Vincent and the Grenadines','s27'
'St. Vincent and the Grenadines','s28'
'St. Vincent and the Grenadines','s29'
'Samoa','s1'
'Samoa','s2'
'Samoa','s3'
'Samoa','s4'
'Samoa','s5'
'Samoa','s6'
'Samoa','s7'
'Samoa','s8'
'Samoa','s9'
'Samoa','s10'
'Samoa','s11'
'Samoa','s12'
'Samoa','s13'
'Samoa','s14'
'Samoa','s15'
'Samoa','s16'
'Samoa','s17'
'Samoa','s18'
'Samoa','s19'
'Samoa','s20'
'San Marino','s1'
'San Marino','s2'
'San Marino','s3'
'San Marino','s4'
'San Marino','s5'
'San Marino','s6'
'San Marino','s7'
'San Marino','s8'
'San Marino','s9'
'San Marino','s10'
'San Marino','s11'
'San Marino','s12'
'San Marino','s13'
'San Marino','s14'
'San Marino','s15'
'San Marino','s16'
'San Marino','s17'
'San Marino','s18'
'San Marino','s19'
'San Marino','s20'
'San Marino','s21'
'San Marino','s22'
'San Marino','s23'
'San Marino','s24'
'San Marino','s25'
'San Marino','s26'
'San Marino','s27'
'San Marino','s28'
'São Tomé and Príncipe','s1'
'São Tomé and Príncipe','s2'
'São Tomé and Príncipe','s3'
'São Tomé and Príncipe','s4'
'São Tomé and Príncipe','s5'
'São Tomé and Príncipe','s6'
'São Tomé and Príncipe','s7'
'São Tomé and Príncipe','s8'
'São Tomé and Príncipe','s9'
'São Tomé and Príncipe','s10'
'São Tomé and Príncipe','s11'
'São Tomé and Príncipe','s12'
'São Tomé and Príncipe','s13'
'São Tomé and Príncipe','s14'
'São Tomé and Príncipe','s15'
'São Tomé and Príncipe','s16'
'São Tomé and Príncipe','s17'
'São Tomé and Príncipe','s18'
'São Tomé and Príncipe','s19'
'São Tomé and Príncipe','s20'
'São Tomé and Príncipe','s21'
'São Tomé and Príncipe','s22'
'São Tomé and Príncipe','s23'
'São Tomé and Príncipe','s24'
'São Tomé and Príncipe','s25'
'São Tomé and Príncipe','s26'
'São Tomé and Príncipe','s27'
'São Tomé and Príncipe','s28'
'Saudi Arabia','s1'
'Saudi Arabia','s2'
'Saudi Arabia','s3'
'Saudi Arabia','s4'
'Saudi Arabia','s5'
'Saudi Arabia','s6'
'Saudi Arabia','s7'
'Saudi Arabia','s8'
'Saudi Arabia','s9'
'Saudi Arabia','s10'
'Saudi Arabia','s11'
'Saudi Arabia','s12'
'Saudi Arabia','s13'
'Saudi Arabia','s14'
'Saudi Arabia','s15'
'Saudi Arabia','s16'
'Saudi Arabia','s17'
'Saudi Arabia','s18'
'Saudi Arabia','s19'
'Saudi Arabia','s20'
'Saudi Arabia','s21'
'Saudi Arabia','s22'
'Saudi Arabia','s23'
'Saudi Arabia','s24'
'Saudi Arabia','s25'
'Senegal','s1'
'Senegal','s2'
'Senegal','s3'
'Senegal','s4'
'Senegal','s5'
'Senegal','s6'
'Senegal','s7'
'Senegal','s8'
'Senegal','s9'
'Senegal','s10'
'Senegal','s11'
'Senegal','s12'
'Senegal','s13'
'Senegal','s14'
'Senegal','s15'
'Senegal','s16'
'Senegal','s17'
'Senegal','s18'
'Senegal','s19'
'Senegal','s20'
'Serbia Yugoslav','s1'
'Serbia Yugoslav','s2'
'Serbia Yugoslav','s3'
'Serbia Yugoslav','s4'
'Serbia Yugoslav','s5'
'Serbia Yugoslav','s6'
'Serbia Yugoslav','s7'
'Serbia Yugoslav','s8'
'Serbia Yugoslav','s9'
'Serbia Yugoslav','s10'
'Serbia Yugoslav','s11'
'Serbia Yugoslav','s12'
'Serbia Yugoslav','s13'
'Serbia Yugoslav','s14'
'Serbia Yugoslav','s15'
'Serbia Yugoslav','s16'
'Serbia Yugoslav','s17'
'Serbia Yugoslav','s18'
'Serbia Yugoslav','s19'
'Serbia Yugoslav','s20'
'Serbia Yugoslav','s21'
'Serbia Yugoslav','s22'
'Serbia Yugoslav','s23'
'Serbia Yugoslav','s24'
'Serbia Yugoslav','s25'
'Serbia Yugoslav','s26'
'Serbia Yugoslav','s27'
'Serbia Yugoslav','s28'
'Serbia Yugoslav','s29'
'Seychelles','s1'
'Seychelles','s2'
'Seychelles','s3'
'Seychelles','s4'
'Seychelles','s5'
'Seychelles','s6'
'Seychelles','s7'
'Seychelles','s8'
'Seychelles','s9'
'Seychelles','s10'
'Seychelles','s11'
'Seychelles','s12'
'Seychelles','s13'
'Seychelles','s14'
'Seychelles','s15'
'Seychelles','s16'
'Seychelles','s17'
'Seychelles','s18'
'Seychelles','s19'
'Seychelles','s20'
'Seychelles','s21'
'Seychelles','s22'
'Seychelles','s23'
'Seychelles','s24'
'Seychelles','s25'
'Seychelles','s26'
'Sierra Leone','s1'
'Sierra Leone','s2'
'Sierra Leone','s3'
'Sierra Leone','s4'
'Sierra Leone','s5'
'Sierra Leone','s6'
'Sierra Leone','s7'
'Sierra Leone','s8'
'Sierra Leone','s9'
'Sierra Leone','s10'
'Sierra Leone','s11'
'Sierra Leone','s12'
'Sierra Leone','s13'
'Sierra Leone','s14'
'Sierra Leone','s15'
'Sierra Leone','s16'
'Sierra Leone','s17'
'Sierra Leone','s18'
'Sierra Leone','s19'
'Sierra Leone','s20'
'Sierra Leone','s21'
'Sierra Leone','s22'
'Sierra Leone','s23'
'Singapore','s1'
'Singapore','s2'
'Singapore','s3'
'Singapore','s4'
'Singapore','s5'
'Singapore','s6'
'Singapore','s7'
'Singapore','s8'
'Singapore','s9'
'Singapore','s10'
'Singapore','s11'
'Singapore','s12'
'Singapore','s13'
'Singapore','s14'
'Singapore','s15'
'Singapore','s16'
'Singapore','s17'
'Singapore','s18'
'Singapore','s19'
'Singapore','s20'
'Singapore','s21'
'Singapore','s22'
'Singapore','s23'
'Singapore','s24'
'Singapore','s25'
'Singapore','s26'
'Singapore','s27'
'Singapore','s28'
'Slovakia','s1'
'Slovakia','s2'
'Slovakia','s3'
'Slovakia','s4'
'Slovakia','s5'
'Slovakia','s6'
'Slovakia','s7'
'Slovakia','s8'
'Slovakia','s9'
'Slovakia','s10'
'Slovakia','s11'
'Slovakia','s12'
'Slovakia','s13'
'Slovakia','s14'
'Slovakia','s15'
'Slovakia','s16'
'Slovakia','s17'
'Slovakia','s18'
'Slovakia','s19'
'Slovakia','s20'
'Slovakia','s21'
'Slovakia','s22'
'Slovakia','s23'
'Slovakia','s24'
'Slovakia','s25'
'Slovenia','s1'
'Slovenia','s2'
'Slovenia','s3'
'Slovenia','s4'
'Slovenia','s5'
'Slovenia','s6'
'Slovenia','s7'
'Slovenia','s8'
'Slovenia','s9'
'Slovenia','s10'
'Slovenia','s11'
'Slovenia','s12'
'Slovenia','s13'
'Slovenia','s14'
'Slovenia','s15'
'Slovenia','s16'
'Slovenia','s17'
'Slovenia','s18'
'Slovenia','s19'
'Slovenia','s20'
'Slovenia','s21'
'Slovenia','s22'
'Slovenia','s23'
'Slovenia','s24'
'Slovenia','s25'
'Slovenia','s26'
'Solomon Islands','s1'
'Solomon Islands','s2'
'Solomon Islands','s3'
'Solomon Islands','s4'
'Solomon Islands','s5'
'Solomon Islands','s6'
'Solomon Islands','s7'
'Solomon Islands','s8'
'Solomon Islands','s9'
'Solomon Islands','s10'
'Solomon Islands','s11'
'Solomon Islands','s12'
'Solomon Islands','s13'
'Solomon Islands','s14'
'Solomon Islands','s15'
'Solomon Islands','s16'
'Solomon Islands','s17'
'Solomon Islands','s18'
'Solomon Islands','s19'
'Solomon Islands','s20'
'Solomon Islands','s21'
'Somalia','s1'
'Somalia','s2'
'Somalia','s3'
'Somalia','s4'
'Somalia','s5'
'Somalia','s6'
'Somalia','s7'
'Somalia','s8'
'Somalia','s9'
'Somalia','s10'
'Somalia','s11'
'Somalia','s12'
'Somalia','s13'
'Somalia','s14'
'Somalia','s15'
'Somalia','s16'
'Somalia','s17'
'Somalia','s18'
'Somalia','s19'
'Somalia','s20'
'Somalia','s21'
'South Africa','s1'
'South Africa','s2'
'South Africa','s3'
'South Africa','s4'
'South Africa','s5'
'South Africa','s6'
'South Africa','s7'
'South Africa','s8'
'South Africa','s9'
'South Africa','s10'
'South Africa','s11'
'South Africa','s12'
'South Africa','s13'
'South Africa','s14'
'South Africa','s15'
'South Africa','s16'
'South Africa','s17'
'South Africa','s18'
'South Africa','s19'
'South Africa','s20'
'South Africa','s21'
'South Africa','s22'
'South Africa','s23'
'South Africa','s24'
'South Africa','s25'
'Spain','s1'
'Spain','s2'
'Spain','s3'
'Spain','s4'
'Spain','s5'
'Spain','s6'
'Spain','s7'
'Spain','s8'
'Spain','s9'
'Spain','s10'
'Spain','s11'
'Spain','s12'
'Spain','s13'
'Spain','s14'
'Spain','s15'
'Spain','s16'
'Spain','s17'
'Spain','s18'
'Spain','s19'
'Spain','s20'
'Spain','s21'
'Spain','s22'
'Spain','s23'
'Spain','s24'
'Spain','s25'
'Spain','s26'
'Spain','s27'
'Spain','s28'
'Spain','s29'
'Sri Lanka','s1'
'Sri Lanka','s2'
'Sri Lanka','s3'
'Sri Lanka','s4'
'Sri Lanka','s5'
'Sri Lanka','s6'
'Sri Lanka','s7'
'Sri Lanka','s8'
'Sri Lanka','s9'
'Sri Lanka','s10'
'Sri Lanka','s11'
'Sri Lanka','s12'
'Sri Lanka','s13'
'Sri Lanka','s14'
'Sri Lanka','s15'
'Sri Lanka','s16'
'Sri Lanka','s17'
'Sri Lanka','s18'
'Sri Lanka','s19'
'Sri Lanka','s20'
'Sri Lanka','s21'
'Sri Lanka','s22'
'Sri Lanka','s23'
'Sri Lanka','s24'
'Sri Lanka','s25'
'Sri Lanka','s26'
'Sri Lanka','s27'
'Sri Lanka','s28'
'Sudan','s1'
'Sudan','s2'
'Sudan','s3'
'Sudan','s4'
'Sudan','s5'
'Sudan','s6'
'Sudan','s7'
'Sudan','s8'
'Sudan','s9'
'Sudan','s10'
'Sudan','s11'
'Sudan','s12'
'Sudan','s13'
'Sudan','s14'
'Sudan','s15'
'Sudan','s16'
'Sudan','s17'
'Sudan','s18'
'Sudan','s19'
'Sudan','s20'
'Sudan','s21'
'Sudan','s22'
'Sudan','s23'
'Sudan','s24'
'Suriname','s1'
'Suriname','s2'
'Suriname','s3'
'Suriname','s4'
'Suriname','s5'
'Suriname','s6'
'Suriname','s7'
'Suriname','s8'
'Suriname','s9'
'Suriname','s10'
'Suriname','s11'
'Suriname','s12'
'Suriname','s13'
'Suriname','s14'
'Suriname','s15'
'Suriname','s16'
'Suriname','s17'
'Suriname','s18'
'Suriname','s19'
'Suriname','s20'
'Suriname','s21'
'Suriname','s22'
'Suriname','s23'
'Suriname','s24'
'Suriname','s25'
'Suriname','s26'
'Suriname','s27'
'Suriname','s28'
'Swaziland','s1'
'Swaziland','s2'
'Swaziland','s3'
'Swaziland','s4'
'Swaziland','s5'
'Swaziland','s6'
'Swaziland','s7'
'Swaziland','s8'
'Swaziland','s9'
'Swaziland','s10'
'Swaziland','s11'
'Swaziland','s12'
'Swaziland','s13'
'Swaziland','s14'
'Swaziland','s15'
'Swaziland','s16'
'Swaziland','s17'
'Swaziland','s18'
'Swaziland','s19'
'Swaziland','s20'
'Swaziland','s21'
'Sweden','s1'
'Sweden','s2'
'Sweden','s3'
'Sweden','s4'
'Sweden','s5'
'Sweden','s6'
'Sweden','s7'
'Sweden','s8'
'Sweden','s9'
'Sweden','s10'
'Sweden','s11'
'Sweden','s12'
'Sweden','s13'
'Sweden','s14'
'Sweden','s15'
'Sweden','s16'
'Sweden','s17'
'Sweden','s18'
'Sweden','s19'
'Sweden','s20'
'Switzerland','s1'
'Switzerland','s2'
'Switzerland','s3'
'Switzerland','s4'
'Switzerland','s5'
'Switzerland','s6'
'Switzerland','s7'
'Switzerland','s8'
'Switzerland','s9'
'Switzerland','s10'
'Switzerland','s11'
'Switzerland','s12'
'Switzerland','s13'
'Switzerland','s14'
'Switzerland','s15'
'Switzerland','s16'
'Switzerland','s17'
'Switzerland','s18'
'Switzerland','s19'
'Switzerland','s20'
'Switzerland','s21'
'Switzerland','s22'
'Switzerland','s23'
'Syria','s1'
'Syria','s2'
'Syria','s3'
'Syria','s4'
'Syria','s5'
'Syria','s6'
'Syria','s7'
'Syria','s8'
'Syria','s9'
'Syria','s10'
'Syria','s11'
'Syria','s12'
'Syria','s13'
'Syria','s14'
'Syria','s15'
'Syria','s16'
'Syria','s17'
'Syria','s18'
'Syria','s19'
'Syria','s20'
'Taiwan','s1'
'Taiwan','s2'
'Taiwan','s3'
'Taiwan','s4'
'Taiwan','s5'
'Taiwan','s6'
'Taiwan','s7'
'Taiwan','s8'
'Taiwan','s9'
'Taiwan','s10'
'Taiwan','s11'
'Taiwan','s12'
'Taiwan','s13'
'Taiwan','s14'
'Taiwan','s15'
'Taiwan','s16'
'Taiwan','s17'
'Taiwan','s18'
'Taiwan','s19'
'Taiwan','s20'
'Taiwan','s21'
'Taiwan','s22'
'Taiwan','s23'
'Taiwan','s24'
'Tajikistan','s1'
'Tajikistan','s2'
'Tajikistan','s3'
'Tajikistan','s4'
'Tajikistan','s5'
'Tajikistan','s6'
'Tajikistan','s7'
'Tajikistan','s8'
'Tajikistan','s9'
'Tajikistan','s10'
'Tajikistan','s11'
'Tajikistan','s12'
'Tajikistan','s13'
'Tajikistan','s14'
'Tajikistan','s15'
'Tajikistan','s16'
'Tajikistan','s17'
'Tajikistan','s18'
'Tajikistan','s19'
'Tajikistan','s20'
'Tajikistan','s21'
'Tajikistan','s22'
'Tajikistan','s23'
'Tajikistan','s24'
'Tanzania','s1'
'Tanzania','s2'
'Tanzania','s3'
'Tanzania','s4'
'Tanzania','s5'
'Tanzania','s6'
'Tanzania','s7'
'Tanzania','s8'
'Tanzania','s9'
'Tanzania','s10'
'Tanzania','s11'
'Tanzania','s12'
'Tanzania','s13'
'Tanzania','s14'
'Tanzania','s15'
'Tanzania','s16'
'Tanzania','s17'
'Tanzania','s18'
'Tanzania','s19'
'Tanzania','s20'
'Tanzania','s21'
'Tanzania','s22'
'Tanzania','s23'
'Tanzania','s24'
'Thailand','s1'
'Thailand','s2'
'Thailand','s3'
'Thailand','s4'
'Thailand','s5'
'Thailand','s6'
'Thailand','s7'
'Thailand','s8'
'Thailand','s9'
'Thailand','s10'
'Thailand','s11'
'Thailand','s12'
'Thailand','s13'
'Thailand','s14'
'Thailand','s15'
'Thailand','s16'
'Thailand','s17'
'Thailand','s18'
'Thailand','s19'
'Thailand','s20'
'Thailand','s21'
'Thailand','s22'
'Thailand','s23'
'Thailand','s24'
'Togo','s1'
'Togo','s2'
'Togo','s3'
'Togo','s4'
'Togo','s5'
'Togo','s6'
'Togo','s7'
'Togo','s8'
'Togo','s9'
'Togo','s10'
'Togo','s11'
'Togo','s12'
'Togo','s13'
'Togo','s14'
'Togo','s15'
'Togo','s16'
'Togo','s17'
'Togo','s18'
'Togo','s19'
'Togo','s20'
'Togo','s21'
'Togo','s22'
'Togo','s23'
'Togo','s24'
'Togo','s25'
'Togo','s26'
'Togo','s27'
'Tonga','s1'
'Tonga','s2'
'Tonga','s3'
'Tonga','s4'
'Tonga','s5'
'Tonga','s6'
'Tonga','s7'
'Tonga','s8'
'Tonga','s9'
'Tonga','s10'
'Tonga','s11'
'Tonga','s12'
'Tonga','s13'
'Tonga','s14'
'Tonga','s15'
'Tonga','s16'
'Tonga','s17'
'Tonga','s18'
'Tonga','s19'
'Tonga','s20'
'Tonga','s21'
'Tonga','s22'
'Tonga','s23'
'Tonga','s24'
'Tonga','s25'
'Tonga','s26'
'TrinidadTobago','s1'
'TrinidadTobago','s2'
'TrinidadTobago','s3'
'TrinidadTobago','s4'
'TrinidadTobago','s5'
'TrinidadTobago','s6'
'TrinidadTobago','s7'
'TrinidadTobago','s8'
'TrinidadTobago','s9'
'TrinidadTobago','s10'
'TrinidadTobago','s11'
'TrinidadTobago','s12'
'TrinidadTobago','s13'
'TrinidadTobago','s14'
'TrinidadTobago','s15'
'TrinidadTobago','s16'
'TrinidadTobago','s17'
'TrinidadTobago','s18'
'TrinidadTobago','s19'
'TrinidadTobago','s20'
'TrinidadTobago','s21'
'TrinidadTobago','s22'
'TrinidadTobago','s23'
'Tunisia','s1'
'Tunisia','s2'
'Tunisia','s3'
'Tunisia','s4'
'Tunisia','s5'
'Tunisia','s6'
'Tunisia','s7'
'Tunisia','s8'
'Tunisia','s9'
'Tunisia','s10'
'Tunisia','s11'
'Tunisia','s12'
'Tunisia','s13'
'Tunisia','s14'
'Tunisia','s15'
'Tunisia','s16'
'Tunisia','s17'
'Tunisia','s18'
'Tunisia','s19'
'Tunisia','s20'
'Tunisia','s21'
'Turkey','s1'
'Turkey','s2'
'Turkey','s3'
'Turkey','s4'
'Turkey','s5'
'Turkey','s6'
'Turkey','s7'
'Turkey','s8'
'Turkey','s9'
'Turkey','s10'
'Turkey','s11'
'Turkey','s12'
'Turkey','s13'
'Turkey','s14'
'Turkey','s15'
'Turkey','s16'
'Turkey','s17'
'Turkey','s18'
'Turkey','s19'
'Turkey','s20'
'Turkey','s21'
'Turkey','s22'
'Turkey','s23'
'Turkey','s24'
'Turkey','s25'
'Turkey','s26'
'Turkey','s27'
'Turkmenistan','s1'
'Turkmenistan','s2'
'Turkmenistan','s3'
'Turkmenistan','s4'
'Turkmenistan','s5'
'Turkmenistan','s6'
'Turkmenistan','s7'
'Turkmenistan','s8'
'Turkmenistan','s9'
'Turkmenistan','s10'
'Turkmenistan','s11'
'Turkmenistan','s12'
'Turkmenistan','s13'
'Turkmenistan','s14'
'Turkmenistan','s15'
'Turkmenistan','s16'
'Turkmenistan','s17'
'Turkmenistan','s18'
'Turkmenistan','s19'
'Turkmenistan','s20'
'Turkmenistan','s21'
'Turkmenistan','s22'
'Turkmenistan','s23'
'Turkmenistan','s24'
'Turkmenistan','s25'
'Tuvalu','s1'
'Tuvalu','s2'
'Tuvalu','s3'
'Tuvalu','s4'
'Tuvalu','s5'
'Tuvalu','s6'
'Tuvalu','s7'
'Tuvalu','s8'
'Tuvalu','s9'
'Tuvalu','s10'
'Tuvalu','s11'
'Tuvalu','s12'
'Tuvalu','s13'
'Tuvalu','s14'
'Tuvalu','s15'
'Tuvalu','s16'
'Tuvalu','s17'
'Tuvalu','s18'
'Tuvalu','s19'
'Tuvalu','s20'
'Tuvalu','s21'
'Tuvalu','s22'
'Tuvalu','s23'
'Tuvalu','s24'
'Tuvalu','s25'
'Tuvalu','s26'
'Tuvalu','s27'
'Tuvalu','s28'
'Tuvalu','s29'
'Uganda','s1'
'Uganda','s2'
'Uganda','s3'
'Uganda','s4'
'Uganda','s5'
'Uganda','s6'
'Uganda','s7'
'Uganda','s8'
'Uganda','s9'
'Uganda','s10'
'Uganda','s11'
'Uganda','s12'
'Uganda','s13'
'Uganda','s14'
'Uganda','s15'
'Uganda','s16'
'Uganda','s17'
'Uganda','s18'
'Uganda','s19'
'Uganda','s20'
'Uganda','s21'
'Uganda','s22'
'Uganda','s23'
'Uganda','s24'
'Uganda','s25'
'Uganda','s26'
'Ukraine','s1'
'Ukraine','s2'
'Ukraine','s3'
'Ukraine','s4'
'Ukraine','s5'
'Ukraine','s6'
'Ukraine','s7'
'Ukraine','s8'
'Ukraine','s9'
'Ukraine','s10'
'Ukraine','s11'
'Ukraine','s12'
'Ukraine','s13'
'Ukraine','s14'
'Ukraine','s15'
'Ukraine','s16'
'Ukraine','s17'
'Ukraine','s18'
'Ukraine','s19'
'Ukraine','s20'
'Ukraine','s21'
'Ukraine','s22'
'United Arab Emirates','s1'
'United Arab Emirates','s2'
'United Arab Emirates','s3'
'United Arab Emirates','s4'
'United Arab Emirates','s5'
'United Arab Emirates','s6'
'United Arab Emirates','s7'
'United Arab Emirates','s8'
'United Arab Emirates','s9'
'United Arab Emirates','s10'
'United Arab Emirates','s11'
'United Arab Emirates','s12'
'United Arab Emirates','s13'
'United Arab Emirates','s14'
'United Arab Emirates','s15'
'United Arab Emirates','s16'
'United Arab Emirates','s17'
'United Arab Emirates','s18'
'United Arab Emirates','s19'
'United Arab Emirates','s20'
'United Arab Emirates','s21'
'United Kingdom','s1'
'United Kingdom','s2'
'United Kingdom','s3'
'United Kingdom','s4'
'United Kingdom','s5'
'United Kingdom','s6'
'United Kingdom','s7'
'United Kingdom','s8'
'United Kingdom','s9'
'United Kingdom','s10'
'United Kingdom','s11'
'United Kingdom','s12'
'United Kingdom','s13'
'United Kingdom','s14'
'United Kingdom','s15'
'United Kingdom','s16'
'United Kingdom','s17'
'United Kingdom','s18'
'United Kingdom','s19'
'United Kingdom','s20'
'United Kingdom','s21'
'United Kingdom','s22'
'United Kingdom','s23'
'United Kingdom','s24'
'United Kingdom','s25'
'United Kingdom','s26'
'United Kingdom','s27'
'United States','s1'
'United States','s2'
'United States','s3'
'United States','s4'
'United States','s5'
'United States','s6'
'United States','s7'
'United States','s8'
'United States','s9'
'United States','s10'
'United States','s11'
'United States','s12'
'United States','s13'
'United States','s14'
'United States','s15'
'United States','s16'
'United States','s17'
'United States','s18'
'United States','s19'
'United States','s20'
'United States','s21'
'United States','s22'
'United States','s23'
'United States','s24'
'United States','s25'
'United States','s26'
'United States','s27'
'United States','s28'
'Uruguay','s1'
'Uruguay','s2'
'Uruguay','s3'
'Uruguay','s4'
'Uruguay','s5'
'Uruguay','s6'
'Uruguay','s7'
'Uruguay','s8'
'Uruguay','s9'
'Uruguay','s10'
'Uruguay','s11'
'Uruguay','s12'
'Uruguay','s13'
'Uruguay','s14'
'Uruguay','s15'
'Uruguay','s16'
'Uruguay','s17'
'Uruguay','s18'
'Uruguay','s19'
'Uruguay','s20'
'Uruguay','s21'
'Uruguay','s22'
'Uruguay','s23'
'Uruguay','s24'
'Uruguay','s25'
'Uzbekistan','s1'
'Uzbekistan','s2'
'Uzbekistan','s3'
'Uzbekistan','s4'
'Uzbekistan','s5'
'Uzbekistan','s6'
'Uzbekistan','s7'
'Uzbekistan','s8'
'Uzbekistan','s9'
'Uzbekistan','s10'
'Uzbekistan','s11'
'Uzbekistan','s12'
'Uzbekistan','s13'
'Uzbekistan','s14'
'Uzbekistan','s15'
'Uzbekistan','s16'
'Uzbekistan','s17'
'Uzbekistan','s18'
'Uzbekistan','s19'
'Uzbekistan','s20'
'Uzbekistan','s21'
'Uzbekistan','s22'
'Uzbekistan','s23'
'Uzbekistan','s24'
'Uzbekistan','s25'
'Uzbekistan','s26'
'Uzbekistan','s27'
'Vanuatu','s1'
'Vanuatu','s2'
'Vanuatu','s3'
'Vanuatu','s4'
'Vanuatu','s5'
'Vanuatu','s6'
'Vanuatu','s7'
'Vanuatu','s8'
'Vanuatu','s9'
'Vanuatu','s10'
'Vanuatu','s11'
'Vanuatu','s12'
'Vanuatu','s13'
'Vanuatu','s14'
'Vanuatu','s15'
'Vanuatu','s16'
'Vanuatu','s17'
'Vanuatu','s18'
'Vanuatu','s19'
'Vanuatu','s20'
'Vanuatu','s21'
'Vanuatu','s22'
'Vanuatu','s23'
'Vanuatu','s24'
'Vatican City','s1'
'Vatican City','s2'
'Vatican City','s3'
'Vatican City','s4'
'Vatican City','s5'
'Vatican City','s6'
'Vatican City','s7'
'Vatican City','s8'
'Vatican City','s9'
'Vatican City','s10'
'Vatican City','s11'
'Vatican City','s12'
'Vatican City','s13'
'Vatican City','s14'
'Vatican City','s15'
'Vatican City','s16'
'Vatican City','s17'
'Vatican City','s18'
'Vatican City','s19'
'Vatican City','s20'
'Vatican City','s21'
'Venezuela','s1'
'Venezuela','s2'
'Venezuela','s3'
'Venezuela','s4'
'Venezuela','s5'
'Venezuela','s6'
'Venezuela','s7'
'Venezuela','s8'
'Venezuela','s9'
'Venezuela','s10'
'Venezuela','s11'
'Venezuela','s12'
'Venezuela','s13'
'Venezuela','s14'
'Venezuela','s15'
'Venezuela','s16'
'Venezuela','s17'
'Venezuela','s18'
'Venezuela','s19'
'Venezuela','s20'
'Venezuela','s21'
'Venezuela','s22'
'Venezuela','s23'
'Venezuela','s24'
'Venezuela','s25'
'Venezuela','s26'
'Venezuela','s27'
'Venezuela','s28'
'Vietnam','s1'
'Vietnam','s2'
'Vietnam','s3'
'Vietnam','s4'
'Vietnam','s5'
'Vietnam','s6'
'Vietnam','s7'
'Vietnam','s8'
'Vietnam','s9'
'Vietnam','s10'
'Vietnam','s11'
'Vietnam','s12'
'Vietnam','s13'
'Vietnam','s14'
'Vietnam','s15'
'Vietnam','s16'
'Vietnam','s17'
'Vietnam','s18'
'Vietnam','s19'
'Vietnam','s20'
'Vietnam','s21'
'Vietnam','s22'
'Vietnam','s23'
'Vietnam','s24'
'Vietnam','s25'
'Sahara','s1'
'Sahara','s2'
'Sahara','s3'
'Sahara','s4'
'Sahara','s5'
'Sahara','s6'
'Sahara','s7'
'Sahara','s8'
'Sahara','s9'
'Sahara','s10'
'Sahara','s11'
'Sahara','s12'
'Sahara','s13'
'Sahara','s14'
'Sahara','s15'
'Sahara','s16'
'Sahara','s17'
'Sahara','s18'
'Sahara','s19'
'Sahara','s20'
'Sahara','s21'
'Sahara','s22'
'Sahara','s23'
'Sahara','s24'
'Sahara','s25'
'Sahara','s26'
'Sahara','s27'
'Sahara','s28'
'Sahara','s29'
'Yemen','s1'
'Yemen','s2'
'Yemen','s3'
'Yemen','s4'
'Yemen','s5'
'Yemen','s6'
'Yemen','s7'
'Yemen','s8'
'Yemen','s9'
'Yemen','s10'
'Yemen','s11'
'Yemen','s12'
'Yemen','s13'
'Yemen','s14'
'Yemen','s15'
'Yemen','s16'
'Yemen','s17'
'Yemen','s18'
'Yemen','s19'
'Yemen','s20'
'Yemen','s21'
'Yemen','s22'
'Yemen','s23'
'Yemen','s24'
'Yemen','s25'
'Yemen','s26'
'Yemen','s27'
'Zambia','s1'
'Zambia','s2'
'Zambia','s3'
'Zambia','s4'
'Zambia','s5'
'Zambia','s6'
'Zambia','s7'
'Zambia','s8'
'Zambia','s9'
'Zambia','s10'
'Zambia','s11'
'Zambia','s12'
'Zambia','s13'
'Zambia','s14'
'Zambia','s15'
'Zambia','s16'
'Zambia','s17'
'Zambia','s18'
'Zambia','s19'
'Zambia','s20'
'Zambia','s21'
'Zambia','s22'
'Zambia','s23'
'Zambia','s24'
'Zambia','s25'
'Zimbabwe','s1'
'Zimbabwe','s2'
'Zimbabwe','s3'
'Zimbabwe','s4'
'Zimbabwe','s5'
'Zimbabwe','s6'
'Zimbabwe','s7'
'Zimbabwe','s8'
'Zimbabwe','s9'
'Zimbabwe','s10'
'Zimbabwe','s11'
'Zimbabwe','s12'
'Zimbabwe','s13'
'Zimbabwe','s14'
'Zimbabwe','s15'
'Zimbabwe','s16'
'Zimbabwe','s17'
'Zimbabwe','s18'
'Zimbabwe','s19'
'Zimbabwe','s20'
'Zimbabwe','s21'
'Zimbabwe','s22'
'Zimbabwe','s23'
